### ISSUE TITLE
The requested module 'slash' does not provide an export named 'default'

### ISSUE THREAD

**Issue by vukadinFE** [eirslett/storybook-builder-vite#100]
![image](https://user-images.githubusercontent.com/38419355/134812171-b1e78152-499a-4fbc-ae7d-e55cc3b4f8f4.png)

**Comment by vukadinFE** [comment]
This happens on the fresh project after installation:
`npx sb@next init --builder storybook-builder-vite`

**Comment by IanVS** [comment]
@eirslett, do you want to release a new version with the fix for this?

**Comment by eirslett** [comment]
@IanVS Sure, but (stupid question) how do we release it now that it's converted to yarn? (Maybe we should have som docs about it in the README...)
Both you and @shilman also have full publish rights for putting the package on npm!

**Comment by eirslett** [comment]
ok, never mind! I figured it out and released it now.

**Comment by camiloforero** [comment]
This happens because the `slash` imported version is on CommonJS, if that matters

**Comment by IanVS** [comment]
This is resolved in version 0.1.0.
