### ISSUE TITLE
Docs pages : The docs page does not display the component code "No code available"

### ISSUE THREAD

**Issue by messenjer** [eirslett/storybook-builder-vite#111]
Hello,

In my storybook, the docs page does not display the component code. It displays "No code available" (see capture below)

<img width="1745" alt="Screenshot 2021-10-07 at 09 55 13" src="https://user-images.githubusercontent.com/80677/136406762-8d5405c4-ce03-44f0-ad45-63451715aa03.png">

I manage to reproduce it with a basic installation, I create a "vue3" project with Vite and then I install storybook with the storybook-builder-vite.  In the default examples, I have the same problem.

Here is the commands, I execute in a new folder:

```
npm init vite@latest my-vue-app --template vue-ts
cd my-vue-app
npm install
npx sb@next init --builder storybook-builder-vite
npm run storybook
```

and my package.json

```
{
  "name": "my-vue-app",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit && vite build",
    "serve": "vite preview",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "dependencies": {
    "vue": "^3.2.16"
  },
  "devDependencies": {
    "@babel/core": "^7.15.8",
    "@storybook/addon-actions": "^6.4.0-beta.6",
    "@storybook/addon-essentials": "^6.4.0-beta.6",
    "@storybook/addon-links": "^6.4.0-beta.6",
    "@storybook/vue3": "^6.4.0-beta.6",
    "@vitejs/plugin-vue": "^1.9.2",
    "babel-loader": "^8.2.2",
    "storybook-builder-vite": "^0.1.0",
    "typescript": "^4.4.3",
    "vite": "^2.6.0",
    "vue-loader": "^16.8.1",
    "vue-tsc": "^0.3.0"
  }
}
```

I try also with a react application, and I have the same issue

```
npm init @vitejs/app vite-react-app --template react
cd vite-react-app
npm install
npm run storybook
```

Is it a known problem? Where can I look to fix this, the "vite" configuration? or in the storybook code?

Thanks

Mathieu

**Comment by Psvensso** [comment]
Just shedding some light on this, 
@storybook/addon-docs uses the storySource and @storybook/source-loader to load source and modify the story (adding the storySource parameter to the story).

As the name suggests, the @storybook/source-loader is a Webpack loader. 

So i guess this would have to be totaly re-written for Vite/Esbuild.

**Comment by Nisgrak** [comment]
Same issue, any fix?

**Comment by lk0606** [comment]
Same issue, any fix?
and I use vue3 + tsx, my code here.
help wanted!
https://github.com/wont-org/vue3-el/blob/docs/sb/components/Button/index.stories.tsx

**Comment by lk0606** [comment]
I think, the problem is vue-docgen-api. which used webpack. but vite haven't. @story/docs options is passed under that.

Looking forward to your solution
