### ISSUE TITLE
Resolve failed after update @storybook related dependencies

### ISSUE THREAD

**Issue by zheeeng** [eirslett/storybook-builder-vite#119]
After updating outdated @storybook packages, chrome console report:

```
index.js?v=a3d44ef9:5 Uncaught SyntaxError: The requested module '/@fs/Users/zheeeng/Workspace/foo/node_modules/.pnpm/react-is@17.0.2/node_modules/react-is/index.js?v=a3d44ef9' does not provide an export named 'ForwardRef'
```

![image](https://user-images.githubusercontent.com/1303154/138283152-84a1fb8e-f5f7-4293-81e7-c01a6389dd6c.png)

I trace the generated file that:

http://localhost:6006/@fs/Users/zheeeng/Workspace/foo/node_modules/.pnpm/react-element-to-jsx-string@14.3.4/node_modules/react-element-to-jsx-string/dist/esm/index.js?v=a3d44ef9:
```
import { isSuspense, isStrictMode, isProfiler, isLazy, isContextProvider, isContextConsumer, isMemo, isForwardRef, ForwardRef, Memo } from '/@fs/Users/zheeeng/Workspace/foo/node_modules/.pnpm/react-is@17.0.2/node_modules/react-is/index.js?v=a3d44ef9';
````

http://localhost:6006/@fs/Users/zheeeng/Workspace/foo/node_modules/.pnpm/react-is@17.0.2/node_modules/react-is/index.js?v=a3d44ef9:
```
'use strict';

if ("development" === 'production') {
  module.exports = require('./cjs/react-is.production.min.js');
} else {
  module.exports = require('./cjs/react-is.development.js');
}

```

`react-element-to-jsx-string` uses ESM module format, `react-is` uses CJS module format.

Outdated screenshot:
![image](https://user-images.githubusercontent.com/1303154/138288720-f7a5437a-3042-4165-97d1-66331de67148.png)

**Comment by neilchaudhuri** [comment]
FYI I encountered the same with `react-element-to-jsx-string`. I added it to my `include` entry so I am fine, but just in case you cared to add that as well.

**Comment by IanVS** [comment]
Thanks @neilchaudhuri.  Do you know if this is something that's being brought in by a storybook dependency, or one of your other dependencies?  We only really want to add dependencies to our list that we know is storybook-related.  Everything else will need to be handled the way you have done, in the user's `viteFinal`.

**Comment by neilchaudhuri** [comment]
It appears to be a dependency of `@storybook/addon-docs`.

Coincidentally, I have an [open issue](https://github.com/storybookjs/storybook/issues/16716) in Storybook proper for the same addon
