### ISSUE TITLE
Supporting storyStoreV7

### ISSUE THREAD

**Issue by joshwooding** [eirslett/storybook-builder-vite#125]
Has there been any discussions around supporting storyStoreV7? I know I might be jumping the gun a little since it's still in beta :) 

I know @tmeasday mentioned it [here](https://github.com/eirslett/storybook-builder-vite/issues/95#issuecomment-919573222) but curious if there's been any more discussion?

**Comment by IanVS** [comment]
Released in version 0.1.8!
