### ISSUE TITLE
MDX transformation fails

### ISSUE THREAD

**Issue by sveisvei** [eirslett/storybook-builder-vite#13]
Running the code in the readme and then building the static version does not work out of the box.

Does output "unexpected" large output as well.

<img width="1000" alt="Skjermbilde 2021-04-28 kl  19 16 42" src="https://user-images.githubusercontent.com/121438/116445647-64feb500-a856-11eb-9e2a-bfd80df208e7.png">

vs without the mdx file:

<img width="748" alt="Skjermbilde 2021-04-28 kl  19 19 11" src="https://user-images.githubusercontent.com/121438/116445919-b1e28b80-a856-11eb-8285-54f4dbf2af94.png">

**Comment by eirslett** [comment]
Takk for sist! 😃 

Is this with the latest version of Storybook (6.3-alpha-something) and the latest version of the builder? What about it is not working? MDX should at least work in development mode, I haven't checked the static build yet.

I agree that the file sizes look pretty huge. Maybe the addon-docs component itself is pretty heavy? We should compare the numbers to the Webpack version, I'm not sure if the large bundle size is Vite's fault or not.

**Comment by sveisvei** [comment]
Takk for sist  ja, tiden flyr :)!

It was just an observation, I have not checked what the expected size is yet - will check this soon.

**Comment by lmestel** [comment]
Hi,

running the react example with a MDX story results in an empty Docs page and `Uncaught TypeError: Cannot read property 'fromId' of undefined`. Canvas looks good.

![Bildschirmfoto 2021-06-17 um 12 39 12](https://user-images.githubusercontent.com/31414552/122381756-90a23f80-cf69-11eb-8537-a030250d6b5c.png)

Here is a repo to reproduce: https://github.com/lmestel/storybook-builder-vite (with a Button.stories.mdx in the example-react package)

**Comment by eirslett** [comment]
I wonder if this could be related to Typescript-docgen-plugin or something like that? It's still missing in the Vite builder...

**Comment by shilman** [comment]
There is code in the preview that sets up a react context called `DocsContext` with a storyStore, and somehow that isn't getting set properly in the vite-builder:

https://github.com/storybookjs/storybook/blob/next/lib/core-client/src/preview/StoryRenderer.tsx#L320

**Comment by eirslett** [comment]
This should be fixed in the latest release (with Storybook 6.3.4 or newer)
