### ISSUE TITLE
Unable to load stories. Error on loading 'synchronous-promise' module

### ISSUE THREAD

**Issue by gustavo-pateti** [eirslett/storybook-builder-vite#132]
Fresh  install (builder version: ^0.1.3) on Vite^2.6.0.

When running storybook, it hangs on the loading spinner, and the console logs this:

`Uncaught SyntaxError: The requested module '/node_modules/synchronous-promise/index.js?v=ad7b1f28' does not provide an export named 'SynchronousPromise'`

With the offending line being:

`StoryStore.js?v=ad7b1f28:62`

Any idea or fix that can help? Thanks in advance.

**Comment by IanVS** [comment]
You should be able to add it to `optimizeDeps.include` in your viteFinal.  Just be sure to spread in the existing ones, search issues for some examples of how if you're not certain.

**Comment by gustavo-pateti** [comment]
Thanks! solved by using `optimizeDeps.include`.

**Comment by jackmellis** [comment]
I am having this issue after recently upgrading. I added this to the include array, then the next library, then the next. After adding 20 libraries to the include array, I'm starting to think there's something else amiss here 👀

**Comment by IanVS** [comment]
@jackmellis can you share the part of your viteFinal where you are adding them?
