### ISSUE TITLE
Storybook 6.2.9 seems to try to load storybook-builder-vite from an incorrect module

### ISSUE THREAD

**Issue by tjlittle** [eirslett/storybook-builder-vite#14]
I'm testing out storybook-builder-vite in a skeleton sveltekit project.

In the instructions, .storybook/main.js (.storybook/main.cjs for me) should be configured as

```js
  core: {
    builder: 'storybook-builder-vite',
  },
```

However, storybook 6.2.9 seems to interpolate this configuration into the module name `@storybook/builder-storybook-builder-vite`.

As a workaround, I installed storybook-builder-vite with an alias using the following.

`npm i -D @storybook/builder-storybook-builder-vite@npm:storybook-builder-vite`

**Comment by tjlittle** [comment]
I'm not sure if my workaround is effective, because although storybook seems to run/start, it never fully loads. The browser console fills up with errors like the following:

`VM3147 client:184 WebSocket connection to 'ws://localhost:6006/' failed: `

**Comment by shilman** [comment]
`storybook-builder-vite` needs 6.3 alpha AFAIK

**Comment by tjlittle** [comment]
Thanks @shilman! Installing `6.3.0-alpha.16` did the trick for fixing the issue.
