### ISSUE TITLE
parameters.fileName is null

### ISSUE THREAD

**Issue by wild-nyankoman** [eirslett/storybook-builder-vite#142]
hello.
As you can see in the screenshot, `parameters.fileName` is null.
Add-ons that depend on'fileName' won't work.
(e.g. storybook-addon-playwright )

![image](https://user-images.githubusercontent.com/87790123/140675706-f0e77601-ecfe-4331-a31a-db84e0905dd3.png)

story source
```
const Template: ComponentStory<typeof Button> = function (args) {
  console.log(arguments);
  return <Button {...args} />;
};
```

I have patched `codegen-iframe-script.js` as follows.

add this code in line 56.
```
        const cwd = process.cwd();
        const resolveMap = storyEntries.reduce((prev, entry) => ({...prev, [entry]: entry.replace(cwd, '.') }), {});
        const modules = storyEntries.map((entry, i) => `${JSON.stringify(entry)}: story_${i}`).join(',')
        const loadable = `
        (() => {
          const loadable = function(key) {
            return {${modules}}[key];
          };
          Object.assign(loadable, {
            keys: () => (${JSON.stringify(Object.keys(resolveMap))}),
            resolve: (key) => (${JSON.stringify(resolveMap)}[key])
          });
          return loadable;
        })()`;
```

change line 112.
```
    configure(${loadable}, { hot: import.meta.hot }, false); // not sure if the import.meta.hot thing is correct
    `.trim();
        return code;
    };
```

**Comment by joshwooding** [comment]
While this is still broken when storyStoreV7 is not enabled. When it is enabled it works as expected :)

![image](https://user-images.githubusercontent.com/12938082/142708625-2f699732-40df-457e-ba17-bcb0b0b177cb.png)
