### ISSUE TITLE
yarn.lock all package update please

### ISSUE THREAD

**Issue by productdevbook** [eirslett/storybook-builder-vite#145]
<img width="382" alt="CleanShot 2021-11-09 at 13 10 31@2x" src="https://user-images.githubusercontent.com/38668796/140905079-dedd8d8d-45b9-4473-be06-3f7589f5b578.png">

old version :/ all 

new 1.9.4

**Comment by IanVS** [comment]
Hi, the yarn.lock in this package won't be used in your application.  It's only used for developers when working on the builder itself.
