### ISSUE TITLE
Example request for using PNPM and monerepo.

### ISSUE THREAD

**Issue by zheeeng** [eirslett/storybook-builder-vite#149]
At present, after switching yarn to pnpm can't startup a basic project.

**Comment by IanVS** [comment]
There are some other issues with workarounds already posted regarding shamefully_hoist and some settings you can change in viteFinal.  A search through the issues should turn them up.

**Comment by zheeeng** [comment]
> There are some other issues with workarounds already posted regarding shamefully_hoist and some settings you can change in viteFinal. A search through the issues should turn them up.

There still are some pre-bundling issues, it's very slow to bundle cjs modules and huge amount of page reloading.  Hope there is a best practice repo for reference.

**Comment by IanVS** [comment]
>it's very slow to bundle cjs modules and caused huge amount of page reloading

It sounds like you should add these packages to your `optimizedDeps.include` in the `viteFinal` config.  Have you tried that?

**Comment by joshwooding** [comment]
Closing this as stale. We can reopen if there's any action to take.
