### ISSUE TITLE
(storybook-vite-source-loader-plugin) was used to transform files, but didn't generate a sourcemap for the transformation. 

### ISSUE THREAD

**Issue by IanVS** [eirslett/storybook-builder-vite#150]
After updating to  0.1.6, I'm seeing a bunch of these messages when I build storybook:

```
Sourcemap is likely to be incorrect: a plugin (storybook-vite-source-loader-plugin) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```

I believe this is due to https://github.com/eirslett/storybook-builder-vite/pull/147/files#diff-a2d57598d88761951c261c618791586a6bfae721ad14099e08fba7d81d05aa30R20, which does not return a `map`.

**Comment by eirslett** [comment]
@simenbrekken we might have to construct a source map of some sort here
