### ISSUE TITLE
[StoryStoreV7] TypeError: importers[path] is not a function

### ISSUE THREAD

**Issue by IanVS** [eirslett/storybook-builder-vite#155]
I'm testing out 0.1.8 in my app with storyStoreV7 enabled, and it mostly works, except for one story which I have in my `.storybook` folder.  I added a console log to `importFn`, and the path being provided is `.storybook/Introduction.stories.mdx`, but the path in the `importers` object is `./.storybook/Introduction.stories.mdx`.  All the other stories seem to work fine, so I wonder if storybook is handling stories in the `.storybook` folder differently than the others, or if it's a general issue with folders starting with `.`.

**Comment by IanVS** [comment]
I've been trying to dig through the storybook source to figure out why there's no leading `./` on the `.storybook` folder file path.  So far I've made it to here, but I can't figure out where this fileName is being generated.  https://github.com/storybookjs/storybook/blob/7e6bf86244e581f7451ebe43a869b31a2cdc6afd/lib/client-api/src/StoryStoreFacade.ts#L190

**Comment by joshwooding** [comment]
`@storybook/*@v6.4.0-rc.7` is out which should fix this :) 🎉
