### ISSUE TITLE
NPM is missing README

### ISSUE THREAD

**Issue by moltar** [eirslett/storybook-builder-vite#158]
https://www.npmjs.com/package/storybook-builder-vite

![screenshot-20211119T122026-SOWK5m3X](https://user-images.githubusercontent.com/491247/142569519-6f7591b6-0889-4540-b9f2-3a6f9e2c09b5.png)

**Comment by eirslett** [comment]
Oh... can you see if it's possible to configure yarn so that it publishes the README at the root level of the project? Or should we have a separate README inside the builder (not optimal...)?

**Comment by moltar** [comment]
You just need to make sure the README is picked up by publish command as part of the final bundle. Maybe it's excluded? Or it might be outside of your build dir.

**Comment by moltar** [comment]
You can click Explore tab on NPM to see the final published artifact.

![screenshot-20211119T190138-9sSBsDna](https://user-images.githubusercontent.com/491247/142619669-a0199228-7508-4a24-82d0-e0be6ba28dfc.png)

**Comment by IanVS** [comment]
This is fixed now, thanks for bringing it to our attention!

![image](https://user-images.githubusercontent.com/4616705/142698577-c03c4691-cf0f-4947-980e-603d484a3a78.png)
