### ISSUE TITLE
Errors when using 6.4.0-rc.4

### ISSUE THREAD

**Issue by joshwooding** [eirslett/storybook-builder-vite#159]
Since `stringifyEnvs` was removed in https://github.com/storybookjs/storybook/pull/16725/files. https://github.com/eirslett/storybook-builder-vite/blob/b67015a99d798c7cb2f7e5ccf3b3b04b595013a1/packages/storybook-builder-vite/envs.js#L19-L21 will no longer work.

**Comment by shilman** [comment]
Ack. Sorry I'll add it back

**Comment by joshwooding** [comment]
Fixed in storybookjs/storybook#16731
