### ISSUE TITLE
storybook-vite-source-loader-plugin + CSF3

### ISSUE THREAD

**Issue by scott-lc** [eirslett/storybook-builder-vite#164]
I found an issue that works fine in Storybook `6.4.0-rc.6` + Webpack but fails with `storybook-builder-vite`.

The underlying issue is at https://github.com/eirslett/storybook-builder-vite/blob/c2e9c3cc9c7879047e793a2c441a1cdd39f576e2/packages/storybook-builder-vite/source-loader-plugin.js#L10

The `inject` function from `@storybook/source-loader` does not export a `sourceJson` property.  I don't think it ever did.  But regardless, things still generally works.

However, if I upgrade the storybook dependencies (see #161) and create a Storybook 6.4 [Component Story Format 3.0](https://storybook.js.org/blog/component-story-format-3-0/) (CSF3) test, `storybook-builder-vite` does not properly transform the story file and ends up causing Storybook to crash with a `defaultExport is undefined` message.

The following is a valid CSF3 story:

```
export default {
  title: 'Gizmo',
  render: ({ label, ...props }) => <button {...props}>{label}</button>
};

export const Default = {
  args: {
    label: 'Hello, World'
  }
};
```

The key thing to note is that there is no function export (`StoryFn`), just a CSF3 `StoryObj` export.  When transformed by `storybook-vite-source-loader-plugin` the resulting JS file is:

```
var __STORY__ = void 0;
var __LOCATIONS_MAP__ = {};
;
export const __namedExportsOrder = [];
``` 

I believe this has to do with the plugin bypassing the ["standard" Storybook transformer](https://github.com/storybookjs/storybook/blob/282e716e518b332325be97fd691807d2f76fc250/lib/source-loader/src/build.js#L3) and trying to do its own thing.

Oddly enough, if you add a standard function export (`StoryFn`), things actually work, including the CSF3 (`StoryObj`) export.

```
...
export const Weird = () => <div>Don't know why this "fixes" it.</div>;
```

**Comment by IanVS** [comment]
Thanks for bringing this up.  Is this a react project?  I wonder if this has something to do with the vite react plugin looking for an exported component.  I know that was an issue for a while with the older vite react-fast-refresh plugin.

**Comment by joshwooding** [comment]
Maybe we are missing
https://github.com/storybookjs/storybook/blob/c67c22afa75728eb00d782e88b4d43645d3a3253/lib/source-loader/src/build.js#L10-L12

**Comment by scott-lc** [comment]
@IanVS 

>  Is this a react project?

Yes

**Comment by IanVS** [comment]
I have this issue in my own project too, and just didn't notice it before.  I'll try to see if I can figure out a fix.

**Comment by scott-lc** [comment]
This fixed it for me in my environment:

https://github.com/scott-lc/storybook-builder-vite/commit/693464809952c5c7595ae942b5cc61b5da1ce1d7

But I am also running it against Storybook `6.4.0-rc.6` locally to work around [this](https://github.com/eirslett/storybook-builder-vite/issues/161) issue - #161

**Comment by joshwooding** [comment]
I have a local fix too which respects @storybook/source-loader's encapsulation a bit more https://github.com/joshwooding/storybook-builder-vite/blob/6e4a1c8ee8e778fcd3cf70ac08fb08b2570c9d43/packages/storybook-builder-vite/source-loader-plugin.js#L12

**Comment by scott-lc** [comment]
@joshwooding - That is a _much_ better solution and works perfectly for me.  

I was under the impression that the `transform` could not be `async`, which was why that other solution existed in the first place.

**Comment by IanVS** [comment]
Great teamwork!  @joshwooding I'll review a PR if you would like to submit it.
