### ISSUE TITLE
Svelte storybook typescript problem "Internal server error: ... Unexpected token"

### ISSUE THREAD

**Issue by rottmann** [eirslett/storybook-builder-vite#179]
When i set a type on export i got an error, i am not sure if it is a builder or ts problem. But in vs code editor or  when i run my app, everything is ok when i set the type, so i think it is a problem from the builder or storybook (or my misconfiguration).

icon.svelte (this works)
```svelte
<script lang="ts">
  export let src = []
</script>
```

icon.svelte (this not)
```svelte
<script lang="ts">
  export let src: any[] = []
</script>
```

Error:
```
18:07:16 [vite] ✨ dependencies updated, reloading page...
18:07:31 [vite] Internal server error: /home/rottmann/git/app/src/components/icon/icon.svelte:11:16 Unexpected token
  Plugin: vite-plugin-svelte
  File: /home/rottmann/git/app/src/components/icon/icon.svelte
   11 |    export let src: any[] = []
```

./storybook/main.cjs
```js
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx|svelte)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-svelte-csf"
  ],
  "framework": "@storybook/svelte",
  "core": {
    "builder": "storybook-builder-vite"
  },
  "svelteOptions": {
    "preprocess": require("svelte-preprocess")({
      typescript: true,
      postcss: true,
      sourceMap: true
    })
  }
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "esnext",
    "target": "esnext",
    "importsNotUsedAsValues": "error",
    "isolatedModules": true,
    "resolveJsonModule": true,
    "sourceMap": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "outDir": "./dist",
    "baseUrl": "./src",
    "allowJs": true,
    "checkJs": true,
    "paths": {
      "svelte": [ "node_modules/svelte" ],
      "~/*": [ "*" ]
    },
    "strict": true,
    "types": [ "node", "vite/client" ]
  },
  "include": [
    "src/**/*.d.ts",
    "src/**/*.js",
    "src/**/*.ts",
    "src/**/*.svelte"
  ],
  "exclude": [
    "dist",
    "node_modules"
  ]
}
```

Installed with: `npx sb init --builder storybook-builder-vite`

Versions:
storybook-builder-vite 0.1.11
typescript 4.5.3

**Comment by IanVS** [comment]
I doubt this is the cause, but I see `[vite] ✨ dependencies updated, reloading page...`, which means that not all of the dependencies were pre-bundled.  On a line above that, you should see a message about which new dependencies were found.  Try adding those to your `optimizeDeps.include` in `viteFinal`, see https://github.com/eirslett/storybook-builder-vite/issues/173#issuecomment-989264127 for an example.  

Other than that, I'm not sure what else might be going on here.  Perhaps someone with some more svelte experience can chime in?

**Comment by rottmann** [comment]
Added the dependencies in viteFinal and the `18:07:16 [vite] ✨ dependencies updated, reloading page..` message is gone.

But the TypeScript problem still exists.

**Comment by rottmann** [comment]
I traced the `svelteOptions` and got `undefined` here:

https://github.com/eirslett/storybook-builder-vite/blob/628e716705219d6438e571b48b9b2dfd42f29698/packages/storybook-builder-vite/vite-config.js#L33

It seems that the configuration is not passed through `svelteOptions`, and typescript is then not rendered.

**Comment by IanVS** [comment]
Good catch, I've opened #180 with a fix.  Maybe you can try the changes out in your own `node_modules` and see if it works in your project?

**Comment by rottmann** [comment]
Thank you! Can confirm it works.
