### ISSUE TITLE
'/node_modules/path/path.js?v=1a0c7ffe' does not provide an export named 'default'

### ISSUE THREAD

**Issue by aarbour** [eirslett/storybook-builder-vite#183]
I am not sure why I am getting this issue. If I remove path as a node module, storybook works fine with vite. If I add path back it no longer works.

Uncaught SyntaxError: The requested module '/node_modules/path/path.js?v=1a0c7ffe' does not provide an export named 'default'

Storybook 6.4.9
Vie Builder: 0.1.11

**Comment by IanVS** [comment]
Try adding it to your optimizeDeps.include.  the error means that vite is not pre-bundling it.

**Comment by aarbour** [comment]
This worked. Thank you for the quick reply.
