### ISSUE TITLE
Vite:vue plugin throws error

### ISSUE THREAD

**Issue by dprbook** [eirslett/storybook-builder-vite#192]
Hello there,

I seem to have found an issue with using the vite:vue plugin inside storybook. 

When importing the config and plugins from "../vite.config.ts" it throws a "[Vue warn]: Component is missing template or render function."-warning and does not render the component.
The solution I found was to remove the vite:vue plugin or overwrite the plugins as a whole.

I do this to have the vite plugins defined in "vite.config.ts" and also have them available inside storybook. 

I'm using "unplugin-vue-components" here as an example plugin, but it shouldn't matter which plugin.

@/.storybook/main.js

```js
const { loadConfigFromFile, mergeConfig } = require("vite");
const path = require("path");

module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
  framework: "@storybook/vue3",
  core: {
    builder: "storybook-builder-vite",
  },
  async viteFinal(config) {
    const { config: userConfig } = await loadConfigFromFile(
      path.resolve(__dirname, "../vite.config.ts")
    );

    // Commenting this line results in warning
    userConfig.plugins =
      userConfig.plugins?.filter((plugin) => plugin.name !== "vite:vue") ?? [];

    config = mergeConfig(config, {
      ...userConfig,
    });

    // Alternatively, this works but empties the plugins
    // config = mergeConfig(config, {
    //   ...userConfig,
    //   plugins: []
    // });

    return config;
  },
};
```

@/vite.config.ts

```ts
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import Components from "unplugin-vue-components/vite";

export default defineConfig({
  plugins: [
    vue(),
    Components({
      dirs: ["./src/components"],
    }),
  ],
});
```

You can also view this in my example repo:
https://github.com/dprbook/sb

The questions now are: 
1. Did I do something wrong? Overlook some config for example.
2. If not, how to resolve this? Docs or PR?

Best regards,
Daniel

**Comment by joshwooding** [comment]
Hi @dprbook, I believe this is caused by duplicate `@vitejs/plugin-vue`s. This is because it's included by storybook-builder-vite and it's in your `vite.config.ts.`

**Comment by Mastercuber** [comment]
If it's a problem with duplicated dependencies: With `vite` it is possible to deduplicate. See https://vitejs.dev/config/#resolve-dedupe

**Comment by blowsie** [comment]
I tried to dedupe this as suggested and still get this error
```
   config.resolve.dedupe = ["@storybook/client-api", "@vitejs/plugin-vue"]
   ```

**Comment by joshwooding** [comment]
@blowsie I don't think `resolve.dedupe` would fix this. This is caused by having two instances of `@vitejs/plugin-vue` in the vite config.

**Comment by blowsie** [comment]
@joshwooding any suggestions on how we can work around or fix this issue?

**Comment by joshwooding** [comment]
> @joshwooding any suggestions on how we can work around or fix this issue?

@blowsie you would have to figure out why the plugin is being included twice and, remove one instance of it. If you need to configure the plugin, you need to remove the one automatically added by the builder since you can't configure it directly.

**Comment by blowsie** [comment]
> > @joshwooding any suggestions on how we can work around or fix this issue?
> 
> @blowsie you would have to figure out why the plugin is being included twice and, remove one instance of it. If you need to configure the plugin, you need to remove the one automatically added by the builder since you can't configure it directly.

Interestingly, when I removed the plugin from the storybook/main.js I ran into an issue with the render function.
```$setup.t is not a function```

![image](https://user-images.githubusercontent.com/308572/149950731-8504fc89-a9b4-490a-bc53-69cdcc2f6b20.png)

**Comment by joshwooding** [comment]
> > > @joshwooding any suggestions on how we can work around or fix this issue?
> > 
> > 
> > @blowsie you would have to figure out why the plugin is being included twice and, remove one instance of it. If you need to configure the plugin, you need to remove the one automatically added by the builder since you can't configure it directly.
> 
> Interestingly, when I removed the plugin from the storybook/main.js I ran into an issue with the render function. `$setup.t is not a function`

@blowsie Do you have a reproduction I can look at?

**Comment by joshwooding** [comment]
I'm going to close this as being stale for now. Let me know if you can produce a reproduction @blowsie
