### ISSUE TITLE
argsEnhancers was not supported :( !

### ISSUE THREAD

**Issue by IanVS** [eirslett/storybook-builder-vite#20]
It seems like this is a [change](https://github.com/storybookjs/storybook/commit/f33a2f577dcc284e1fbe71cae16ebd7470e8d3d0) in 6.3.0-alpha.31 that is not yet [accounted for](https://github.com/eirslett/storybook-builder-vite/blob/d03eb46634ea50a8b5c37f2536e98cbb438a9ac0/packages/storybook-builder-vite/codegen-iframe-script.js#L88) in this builder.

I can try my hand at a PR if that's helpful...

**Comment by IanVS** [comment]
Hmmm, I tried to do something like this:

```
case 'argsEnhancers': {
try {
  // dynamic import because client-api is not a dependency, and it might not be the right version.
  const {addArgsEnhancer} = await import('@storybook/client-api');
  return value.forEach((enhancer) => addArgsEnhancer(enhancer))
} catch (error) {
  console.error(error);
}
}
```

But then I get an error:

```
Cannot add an args enhancer to the store after a story has been added
```

So I'm not sure what the correct fix here is.

**Comment by eirslett** [comment]
Does it work if you use a static import instead of a dynamic import? If you look at the generated code, it already imports other things from `@storybook/client-api`?

**Comment by IanVS** [comment]
I can try it, but then I think client-api should be added as a dependency, right?

**Comment by IanVS** [comment]
That does remove the warning, but I still can't get my stories to load.  I see some warnings and deprecation messages, but no errors now.

**Comment by eirslett** [comment]
I think you get client-api out of the box with the other storybook dependencies. You shouldn't need to add it manually as a dependency.

**Comment by IanVS** [comment]
But can we guarantee that it will be the correct version (6.3.0-alpha.31 or above)?  If we make this change, and don't add client-cli as a dependency, then I think we need to add a `peerDependency` for it (along with storybook itself, maybe, since this builder requires at least an alpha build of 6.3.0).

**Comment by eirslett** [comment]
I think we can expect the dependency to be included (transitively, in some form) but not really guarantee that it's version alpha.31 or above. Storybook 6.3 final will probably be released soon, and from then on we can simply assert that the builder only works with Storybook 6.3 or newer.
