### ISSUE TITLE
Autotitle when not using storyStoreV7

### ISSUE THREAD

**Issue by IanVS** [eirslett/storybook-builder-vite#201]
Currently, autotitle does not work without enabling storyStoreV7.  We need to provide a global `STORIES` like the webpack builder does here: https://github.com/storybookjs/storybook/blob/e0c0a1429dc123219dfd74c8c4a1c6bfc9660f74/lib/builder-webpack4/src/preview/iframe-webpack.config.ts#L191-L194, so that it can be used here: https://github.com/storybookjs/storybook/blob/e0c0a1429dc123219dfd74c8c4a1c6bfc9660f74/lib/client-api/src/StoryStoreFacade.ts#L156-L164

I've hit two snags so far.  One, is that autoTitle uses `path`, which webpack polyfills but vite does not (there's a simple solution I have working, and I'll submit a PR to storybook soon).  Second, the format of the loadable function we are providing to the call to `configure` does not include the filenames, which means that autoTitle does not name the stories correctly, defaulting to `export_map_1`, rather than the actual filename.  Here is where the loadable is used: https://github.com/storybookjs/storybook/blob/e0c0a1429dc123219dfd74c8c4a1c6bfc9660f74/lib/core-client/src/preview/executeLoadable.ts#L12, and this is how we are currently setting it up: https://github.com/eirslett/storybook-builder-vite/blob/fb289c1cb57c3b929eb5f586e87b7644f97e28be/packages/storybook-builder-vite/codegen-iframe-script.ts#L103-L106.

**Comment by joshwooding** [comment]
The second snag is reported here with a potential solution https://github.com/eirslett/storybook-builder-vite/issues/142

**Comment by IanVS** [comment]
PR to remove `path`: https://github.com/storybookjs/storybook/pull/17185
