### ISSUE TITLE
React is not defined

### ISSUE THREAD

**Issue by hypeJunction** [eirslett/storybook-builder-vite#207]
I hope you can help me figure this one out.
Everything works perfectly in dev mode, but if I build the project, I end up with `React is not defined` error. The issue happens when I try to import `OverlayProvider` from `@react-aria/overlays`. Not sure what exactly the problem is. Tried adding `react` as an alias, but it doesn't help. Also not sure what the difference is between dev and prod config that would account for this. Any thoughts?

**Comment by IanVS** [comment]
@hypeJunction can you provide a reproduction?  It's hard to say what might be going on without seeing your config.

**Comment by hypeJunction** [comment]
Yes, sorry. I should have done it right away. Will report back.

**Comment by hypeJunction** [comment]
Can't reproduce it. Something is fishy with my setup. Will let you know if I discover something.

**Comment by hellowuxin** [comment]
I also have this problem. The issue happens when I try to import `react-custom-scrollbars`. 
I think the problem is related to `var _react = require('react')`

**Comment by IanVS** [comment]
@hellowuxin do you see any messages in your terminal like `[vite] new dependencies found....`?  If so, you'll need to be sure to add those to your `optimizeDeps.include` in `viteFinal`.  Be sure not to overwrite the existing ones in the `config`, though.

**Comment by hypeJunction** [comment]
I ended up switching back to webpack builder, as I have spent hours trying to figure this one out. In my case it was related to react-aria OverlayProvider. For the love of me, I couldn't figure out why it was adding it into vendors with a different module type.

**Comment by IanVS** [comment]
My guess is that vite was not correctly pre-bundling it, which is why I asked about that log message, which would indicate that's what was happening.

**Comment by hellowuxin** [comment]
in dev mode, it prints `[vite] new dependencies found....`, but works well

**Comment by IanVS** [comment]
`[vite] new dependencies found....` indicates that vite was not able to prebundle all of the dependencies.  I really need to add this to the README, but basically, if you see that message, then you should expect a broken storybook.  You'll need to make sure all dependencies are correctly pre-bundled.

**Comment by hellowuxin** [comment]
https://github.com/hellowuxin/storybook-vite-error-demo

**Comment by IanVS** [comment]
Thanks for the reproduction.  I don't think this error is related to the storybook builder.  I added the `Scrollbar` component to the actual app and compiled and previewed with vite (not storybook), and got the same error.  I think that this problem is between react-custom-scrollbars and vite/rollup themselves.

**Comment by bstro** [comment]
For what its worth, I am experiencing the exact same issue as @hypeJunction — trying to import OverlayProvider from `react-aria`, and seeing a `React is not defined` error _only in production builds_.

**Comment by IanVS** [comment]
Sounds like maybe there's something about that particular dependency that isn't set up correctly.  Have you looked at its source and what is being bundled?

**Comment by hypeJunction** [comment]
It seems that somehow the esm module from the dist ends up in vendors. I have rechecked and refactored my code to see if it would help, but at no avail. Somethin in rollup internals causes it to pull the module in, and I have no idea how to debug. My monorepo is so large that I got lost in tracing it down.

**Comment by bstro** [comment]
I upgraded all the dependencies in my project's package.json and the error disappeared. I'm unblocked, but I've also learned nothing.

**Comment by tenphi** [comment]
It happened to me as well. It looks like after migration to the latest Storybook, it requires a separate `vite.config.ts` with the following content:

```
// vite.config.ts
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react({
      jsxRuntime: 'automatic',
    }),
  ],
});
```

Once it's added, the issue is gone.

**Comment by IanVS** [comment]
The fallback framework configs were removed in 8.0.  See the migration doc for details: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#framework-specific-vite-plugins-have-to-be-explicitly-added

**Comment by liaoyinglong** [comment]
For me, the issue was resolved by adding the following code.
```js
  esbuild: {
    jsx: 'automatic',
  },
```

**Comment by jbascue** [comment]
> For me, the issue was resolved by adding the following code.
> 
> ```js
>   esbuild: {
>     jsx: 'automatic',
>   },
> ```

This is all it took for me.

**Comment by chenzewang** [comment]
this is worked for me 👇
```ts
const config: StorybookConfig = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: [
    getAbsolutePath('@storybook/addon-essentials'),
    getAbsolutePath('@storybook/addon-onboarding'),
    getAbsolutePath('@chromatic-com/storybook'),
  ],
  framework: {
    name: getAbsolutePath('@storybook/react-vite'),
    options: {},
  },
  
+ viteFinal: async (config, { configType }) => {
+   config.esbuild = {
+     ...config.esbuild,
+      jsx: 'automatic',
+    };
    return config;
  },
};
```
