### ISSUE TITLE
React HMR bug - doesn't reload storybook iframe

### ISSUE THREAD

**Issue by sukazavr** [eirslett/storybook-builder-vite#212]
Hello!

Minimal bug reproduction repo: https://github.com/sukazavr/storybook-builder-vite-hmr

I face unexpected behavior:
1. Run command `npm run sb`
2. In storybook open `Button / Primary` story
3. Try to change file `src/Button/Button.tsx`
4. It doesn't update component in opened story, it requires manual iframe refreshment
5. This affects every story, you can try to change `src/modules/app/App.tsx`

What I noticed:
1. CSS changes work as expected -- instant update in story
2. Story file updates work as expected
3. Passing `fastRefresh: true` in `react` plugin doesn't fix the issue
4. Experiments with storybook configs were fruitless
5. Vite in dev mode (w/o Storybook) works as expected

Please help me, I'm deadlocked 🤷‍♂️

**Comment by IanVS** [comment]
I'm not able to reproduce using your repo.  I've installed packages with npm, run `npm run sb`, changed the button label, and when I save the change appears instantly with HMR.  Maybe you have some bad state locally?  Or, a browser extension is causing issues?

**Comment by sukazavr** [comment]
Ian thank you very much for checking!
It turned out that it was AdGuard black magic filtration 😭
I tried so many things but hadn't thought about a different layer where is the issue.
