### ISSUE TITLE
HMR seems to be triggered, but storybook doesn't refersh

### ISSUE THREAD

**Issue by openscript** [eirslett/storybook-builder-vite#215]
This has been discussed within a few issues already:

- https://github.com/vitejs/vite/issues/3778
- https://github.com/eirslett/storybook-builder-vite/issues/3

Unfortunately I don't come to a conclusion why inside my project HMR is triggered (console and browser console), but Storybook is not reloaded. I've checked if it works with Webpack and it seems so.

It can (hopefully) be reproduced with:

1. Clone https://github.com/openscript-ch/react-collapsible-timeline
2. Run `yarn install`
3. Start storybook `yarn start`
4. Change a story and see if it's refreshed e. g. `stories/CollapsibleTimeline.stories.tsx` 

Any hint is appreciated :)

**Comment by IanVS** [comment]
I took a look at your repo.  There are two things you should change in your viteFinal:

1. Add `@emotion/react/jsx-dev-runtime` to `optimizeDeps.include`, something like this: 
 ```config.optimizeDeps.include = [...(config.optimizeDeps.include) || [], '@emotion/react/jsx-dev-runtime']```
2. Add `exclude: [/\.stories\.(t|j)sx?$/, /node_modules/],` to your vite react plugin options.  I've edited https://github.com/eirslett/storybook-builder-vite/issues/210#issue-1108420294 to include that line.

**Comment by openscript** [comment]
Thank you Ian for the super quick precise response. It fixes my problem. :smiley:

**Comment by jondot** [comment]
Bumped into this one too - and it helped. @eirslett maybe good to add this to an FAQ?
