### ISSUE TITLE
can't get start with vite get 404 not Found

### ISSUE THREAD

**Issue by Sepush** [eirslett/storybook-builder-vite#225]
I try to move my project to vite use pnpm storybook-builder-vite react
It seems storybook-builder-vite has some error
![image](https://user-images.githubusercontent.com/39197136/151934087-386a44fc-146c-47f7-9bde-3f37f3558604.png)
my repo link is https://github.com/sea-design/sea-design
the main.js is here https://github.com/sea-design/sea-design/blob/main/.storybook/main.js
Is there something wrong with my config?

**Comment by IanVS** [comment]
It looks like you are losing all of the plugins that the builder adds to the config (https://github.com/sea-design/sea-design/blob/211124b4d052e2f1e9687cbe0d9d525f4a8beab5/.storybook/main.js#L25).  Instead, you should find and remove the babel plugin, and re-add it using your config.  For example, in my own config, I use this:

```
    const plugins = [
      ...config.plugins.filter((plugin) => {
        return !(Array.isArray(plugin) && plugin[0].name === 'vite:react-babel');
      }),
      reactPlugin({
        exclude: [/\.stories\.(t|j)sx?$/, /node_modules/],
        babel: { plugins: ['babel-plugin-add-react-displayname'] },
      }),
    ];
```

Note that the builder also includes its own mdx plugin.

**Comment by joshwooding** [comment]
@Sepush Please let us know if this solved your issue. I'll close this for now but happy to re-open if it hasn't.
