### ISSUE TITLE
Svelte nativ stories

### ISSUE THREAD

**Issue by CordlessWool** [eirslett/storybook-builder-vite#231]
Problem:
Svelte natvie stories are not shown in the storybook. This is including the nativ stories of svelte project.
So if I do following steps, only the mdx or js stories get rendered to storybook (tried `mdx`, `js` and `svelte`)
- npm init vite
- npx sb init --builder storybook-builder-vite
- npm run storybook

If I take a look in the config all (also the `.svelte` files) are listet in `optimizeDeeps.entries but the `.svelte` stories are not shown in storybook

**Comment by joshwooding** [comment]
This might be the same issue as https://github.com/eirslett/storybook-builder-vite/issues/224

**Comment by CordlessWool** [comment]
Yes, I tested version 0.1.13 and it works, so I will close this ticket.
As an hint, I tried yesterday also older version 0.1.10, 0.1.2 and 0.1.4. They didn't solve the problem, maybe this will help to find a solution
