### ISSUE TITLE
build-storybook to subfolder results in 404 from iframe.html

### ISSUE THREAD

**Issue by bfanger** [eirslett/storybook-builder-vite#238]
> Failed to load resource: the server responded with a status of 404

/assets/vendor.[hash].js
/assets/iframe.[hash].js
/assets/iframe.[hash].css

**To reproduce:** 
```sh
npx build-storybook  --output-dir build/docs
npx serve@latest build
```
Browse to http://localhost:3000/docs/

**Cause:**  
in the generated build/docs/iframe.html these assets are loaded via absolute urls: `src="/assets/...`

**Possible fix:**. 
Generate relative urls: `src="assets/...` (no leading slash)

**Workaround:**
Running a post build script:
```js
const fs = require('fs');
const filename = 'build/docs/iframe.html';
let html = fs.readFileSync(filename, "utf8");
html = html.replaceAll('"/assets/', '"assets/'); 
fs.writeFileSync(filename, html);
// repeat for other files that use /assets/ urls.
```

**Comment by IanVS** [comment]
Do you see any messages in your terminal like `[vite] found new dependency ...`?

**Comment by IanVS** [comment]
Can you please share your storybook main.js file?

**Comment by bfanger** [comment]
```
// .storybook/main.cjs
const preprocess = require("svelte-preprocess");
const { default: tsconfigPaths } = require("vite-tsconfig-paths");

module.exports = {
  core: {
    builder: "storybook-builder-vite",
  },
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(ts|svelte)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-svelte-csf",
  ],
  svelteOptions: {
    preprocess: preprocess(),
  },
  viteFinal(config) {
    config.plugins.push(tsconfigPaths());
    return config;
  },
};
```
But using https://github.com/jonniebigodes/example-sb-deploy-assets and swapping out the "webpack5" builder with "storybook-builder-vite" might be easier way to reproduce the issue.

**Comment by bfanger** [comment]
Thanks! 
```js
  viteFinal(config) {
    config.base = './';
    return config;
  },
```
works in both `start-storybook` & `build-storybook`, should `base: './'` be the new default for storybook-builder-vite?

**Comment by IanVS** [comment]
Hmmmm, I think we try to deviate as little as possible from the standard vite defaults.  But maybe @eirslett or @joshwooding can chime in whether they think it's worth changing the default here.  It's definitely caught a few people off-guard, and I can't think of any downsides at the moment.

**Comment by IanVS** [comment]
I'll close this for now since it sounds like it's working for you, but we'll keep this on our radar to consider changing.  Thanks for the suggestion, @bfanger.

**Comment by joshwooding** [comment]
I don't have an strong opinions. I think it might be worth keeping an eye on in case we get repeat reports.

**Comment by llaenowyd** [comment]
Hi, just another one hitting this thread.  I want to deploy to github pages, they have a project specific version, then the URL to the static Storybook build would be e.g. `https://llaenowyd.github.io/cushman` and when this page loads it gets 404 on these 2 lines from the index.html:

```html
    <script type="module" crossorigin src="/assets/iframe.3bea89ac.js"></script>
    <link rel="stylesheet" href="/assets/iframe.c2c8282d.css">
```

In this case it would fix it to prepend those links with `./` or `cushman` or `/cushman` ...

But I think it goes back to [this section at the main Storybook site](https://storybook.js.org/docs/react/configure/images-and-assets#absolute-versus-relative-paths):

> Sometimes, you may want to deploy your Storybook into a subpath, like https://example.com/storybook.
>
> In this case, you need to have all your images and media files with relative paths. Otherwise, the browser cannot locate those files.

Wouldn't it be a nice option to have here in this builder, wrt to assets it produces and links to, just make the links relative if enabled.

**Comment by IanVS** [comment]
Hi, just so I understand your proposal, what do you mean by "just make the links relative if enabled"?  If what is enabled?  Do you mean defaulting to `base: ''` in the vite config?

**Comment by llaenowyd** [comment]
> Do you mean defaulting to `base: ''` in the vite config?

I'm glad to learn it's this simple to set up, thanks!

I suppose changing the default behavior could be breaking. Although I couldn't think of how it would break anyone.

And right there's no need for a special option.

**Comment by coreybruyere** [comment]
@llaenowyd were you able to deploy to github pages? Running into the same issue, attempting to change `base`

**Comment by coreybruyere** [comment]
Is this documented anywhere, new to vite and spent a long time trying to filter out irrelevant webpack config + storybook threads until I luckily found this. Happy its an easy fix, maybe I missed

**Comment by IanVS** [comment]
@coreybruyere there are some docs about this at https://vitejs.dev/guide/build.html#public-base-path.

**Comment by andreifilip123** [comment]
I've also had wasted some days figuring out. Happy I found this issue but deploying storybook to a subdirectory should not be this hard. Maybe the docs should be clearer on how to do this. Just wanted to mention that this issue is not that rare 😅 Thanks for the fix @bfanger

**Comment by IanVS** [comment]
This doesn't really have anything to do with storybook, it is a vite option. Maybe you can open an issue in the vite repo?

**Comment by andreifilip123** [comment]
Maybe I'm wrong on this one but in my opinion, the fact that storybook generates assets that are absolute (`/assets/iframe.*.js`) is more of a storybook issue than a vite one.

**Comment by IanVS** [comment]
OK that's fair.  I think we can update the default `base` in storybook 7.0.  I'm reluctant to change it in 6.5, in case anyone is relying on the current default.

**Comment by andreifilip123** [comment]
Totally understandable. But could this be something that can be fixed in the builder-vite repo instead of the storybook main version ? 🤔 I think that for the webpack users, there are more ways to do it than for us, the vite community

**Comment by IanVS** [comment]
builder-vite has moved into the storybook monorepo for 7.0.  This repo here will only be for 6.5.  And yes, I think we can make the change just for vite projects, by setting the default `base` option for vite, which will still let users override it if they need to, using `viteFinal`.
