### ISSUE TITLE
Loading module vite-app.js was blocked because of a disallowed MIME type

### ISSUE THREAD

**Issue by leopsidom** [eirslett/storybook-builder-vite#246]
I'm trying  to add storybook to my existing vue 3 project with this builder. However the storybook only partially load with a spinner on the main page. In the console, I saw the following two errors:

> Loading module from “http://localhost:6006/virtual:/@storybook/builder-vite/vite-app.js” was blocked because of a disallowed MIME type (“text/html”)
> Loading module from “http://localhost:6006/virtual:/@storybook/builder-vite/storybook-stories.js” was blocked because of a disallowed MIME type (“text/html”)

Does anyone know what might be the issue ?

Here is my storybook / main.js:

```
const vue = require('@vitejs/plugin-vue')
const path = require('path');

module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  core: { builder: "storybook-builder-vite" },
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ],
  "framework": "@storybook/vue3",
  async viteFinal(config, { configType }) {
    return {
      ...config,
      plugins: [vue()],
      resolve: {
        alias: {
          '@': path.resolve(__dirname, './src')
        }
      },
    };
  },
}
```

**Comment by IanVS** [comment]
Hi, how are you running the storybook?  I normally see these kinds of errors if I try to open the html file directly in a browser instead of running the storybook dev server or `npx http-server storybook-static` for the built production bundle.

**Comment by IanVS** [comment]
Also, what browser are you using?

**Comment by leopsidom** [comment]
> how are you running the storybook

I run  this command: `npm run storybook`.

> what browser are you using?

Both chrome and firefox give errors. Except chrome gives a different error:

> Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:6006/virtual:/@storybook/builder-vite/vite-app.js

**Comment by IanVS** [comment]
Oh, I looked closer at your config.  You're overriding the existing plugins in `config` in your `viteFinal`.  The vue plugin is already loaded for you, so I think you should be able to just remove that line from your config.  The config also already has a `resolve`, which you should spread in to your config as well.

**Comment by leopsidom** [comment]
Wow nice, that seems to work, thanks! Though I still got a bunch of errors during the initial loading, but it succeeded loading eventually and if I refresh the page, the errors are gone.  Looks like some time out  issue but cool, I think after removing the `plugins` and `resolve`, it now worked!
