### ISSUE TITLE
Singleton client API not yet initialized, cannot call `addArgTypesEnhancer`.

### ISSUE THREAD

**Issue by olemarius** [eirslett/storybook-builder-vite#255]
I'm getting this error with Storybook 6.4.19 for Vue3 started and storybook-builder-vite v0.1.17

ClientApi.js:85 Uncaught Error: Singleton client API not yet initialized, cannot call `addArgTypesEnhancer`.

![image](https://user-images.githubusercontent.com/184536/155405638-de287e62-b0ee-4c21-aefd-f43c75e5581b.png)

Trying to get storybook to work with pnpm. After switching to pnpm and adding the following fix I got the error described:

        // https://github.com/eirslett/storybook-builder-vite/issues/55
        config.root = dirname(require.resolve("storybook-builder-vite"));
        config.server.fsServe = undefined;

**Comment by IanVS** [comment]
This normally means there are more than one copy of `@storybook/client-api` in your `node_modules`.

See https://github.com/eirslett/storybook-builder-vite/pull/254 for a recent fix to this project repo itself.  `pnpm` doesn't seem to like working with this project either though, there have been a few other issues which suggested that it's necessary to shamefully hoist.

**Comment by olemarius** [comment]
@IanVS thanks, I'll have another go at it with shamefully-hoist when #254 is released and let you know how it goes :-)

**Comment by IanVS** [comment]
To be clear, that was a fix for our own monorepo.  It was an example of what you might need to also do in your own project as well.

**Comment by zipme** [comment]
Update packages.json as https://github.com/eirslett/storybook-builder-vite/pull/254/files suggests, and run `pnpm install --shamefully-hoist` and it works! Thanks a lot!

**Comment by IanVS** [comment]
@olemarius were you able to find a solution for your issue?

**Comment by olemarius** [comment]
@IanVS let me give it another go today. I did get it to work with pnpm, but I got some errors from msw that I didn't have time to dig into.

**Comment by olemarius** [comment]
This did the trick! 

```js
config.resolve.dedupe = ["@storybook/client-api"]
```

Storybook 6.4.19 
Vue 3.2.31
storybook-builder-vite 0.1.20

Thanks to https://github.com/eirslett/storybook-builder-vite/issues/50#issuecomment-918158360

**Comment by shadow7412** [comment]
Which config file was that supposed to go in?

**Comment by IanVS** [comment]
@shadow7412 this should not be a problem in recent versions of storybook and @storybook/vite-builder.  If you're having issues, it may mean that you have mismatched storybook versions, causing more than one @storybook/client-api to exist in your node_modules.
