### ISSUE TITLE
*.stories.svelte does not precompile TypeScript

### ISSUE THREAD

**Issue by Tokimon** [eirslett/storybook-builder-vite#258]
I have previously asked the same questions on StackOverflow:
https://stackoverflow.com/questions/70681325/storybook-vite-svelte-typescript-typescript-not-being-processed-in-st/70722451?noredirect=1#comment125676191_70722451

Where I describe how using `import type` in a `*.stories.svelte` file throws an compile error.

In the response to my question @bfanger kindly pointed out that he had made a PR that should fix my problem: #240.
However after upgrading to storybook-builder-vite@0.1.17 (latest version at the time of writing, and should include his PR), the problem still persists. (and it does not seem that this issue is the same as the one the other PR should fix: #224)

Which is why I post this issue here.

The code references has been mentioned in the StackOverflow question and have generally not changed, except I have also tried to just let my `vite.config.js` handle the preprocessing (so removing my attempt to override the preprocessing in the `.storybook/main.cjs`), but to no avail.

So my current config file files are as follows:

**.storybook/main.cjs**
```js
const { resolve } = require('path');

module.exports = {
  stories: [resolve('src/**/*.stories.@(ts|svelte)')],
  addons: ['@storybook/addon-essentials', '@storybook/addon-svelte-csf'],
  core: {
    builder: 'storybook-builder-vite',
  },
  async viteFinal(config) {
    const { default: viteConfig } = await import('../vite.config.js');

    // customize the Vite config here
    config.resolve.alias = viteConfig.resolve?.alias;

    // return the customized config
    return config;
  },
};
```

**vite.config.js**
```js
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { resolve } from 'path';
import sveltePreprocess from 'svelte-preprocess';

// https://vitejs.dev/config/
/**
 * @type {import('vite').UserConfig}
 */
export default {
  plugins: [
    svelte({
      preprocess: [sveltePreprocess()],
    }),
  ],
  resolve: {
    alias: {
      '~': resolve('src'),
    },
  },
  build: {
    outDir: resolve('frontend'),
  },
};
```

Any ideas? Or is this an actual issue?

**Comment by IanVS** [comment]
I believe you'll want to add a `svelteOptions` to your `main.js`, as described here: https://github.com/eirslett/storybook-builder-vite#svelte-customization.

**Comment by Tokimon** [comment]
The bigger question here, is whether this is a problem that lies with `storybook-builder-vite` or `storybook-addon-svelte-csf` ?

**Comment by IanVS** [comment]
I'm not sure, to be honest, I'm not very familiar with svelte.  Maybe @bfanger will have an idea?

**Comment by bfanger** [comment]
Looks like the `source = (await svelte.preprocess(source, svelteOptions.preprocess)).code;` doesn't work as i expected.
I'll investigate tomorrow.
