### ISSUE TITLE
Unable to set environment variables

### ISSUE THREAD

**Issue by angelmeraz** [eirslett/storybook-builder-vite#260]
Similar to https://github.com/storybookjs/storybook/issues/12270, I'm unable to load env vars into storybook, not even with prefix of `STORYBOOK_` ...although this is not necessarily how I'd need them.

In the issue mentioned above, people have found ways of injecting env vars via `webpackFinal(config)` and `plugin.definitions?.['process.env']` but not sure this is possible with `viteFinal()`.

Are there any known ways on how to achieve this?

**Comment by joshwooding** [comment]
Hi, can you please provide a reproduction.

We have an example of loading env vars in all of our examples e.g. https://github.com/eirslett/storybook-builder-vite/blob/main/examples/react/stories/EnvironmentVariables.jsx

**Comment by IanVS** [comment]
Please also see [define](https://vitejs.dev/config/#define) and [envPrefix](https://vitejs.dev/config/#envprefix), which can be set in `viteFinal`.

**Comment by angelmeraz** [comment]
Thanks for the pointers. I was able to get it working with the [_define_](https://vitejs.dev/config/#define) config option.

For other people stumbling upon this, the working config I used in `storybook/main.js`:

```
const path = require('path');
const preprocess = require('svelte-preprocess');
const { viteCommonjs } = require('@originjs/vite-plugin-commonjs');

module.exports = {
  ...,

  async viteFinal(config) {
    ...

    config.define = {
      'process.env.ENV_VAR':  JSON.stringify(process.env.ENV_VAR),
    }

    return config;
  },

  ...
}

```
