### ISSUE TITLE
0.1.17 dropped support for node 12

### ISSUE THREAD

**Issue by joshwooding** [eirslett/storybook-builder-vite#261]
Our build artefacts now contains optional chaining which is only supported in Node 14+.

See https://unpkg.com/storybook-builder-vite@0.1.17/dist/code-generator-plugin.js

```js
            }
        },
        async load(id) {
            const storyStoreV7 = options.features?.storyStoreV7;
            if (id === virtualStoriesFile) {
                if (storyStoreV7) {
                    return (0, codegen_importfn_script_1.generateImportFnScriptCode)(options);
                }
                else {
                    return (0, codegen_entries_1.
```

**Comment by IanVS** [comment]
Node 12 is EOL in 2 months, so hopefully not too many people are still using it, but we should probably adjust our `target` https://github.com/eirslett/storybook-builder-vite/blob/a8e3e215aca13c88532e318e5b7ec2f34b7ec6ff/tsconfig.json#L4 to something more reasonable than ES2021.

**Comment by joshwooding** [comment]
@IanVS Yeah, I agree. I only noticed it because Cloudflare Pages uses 12.18.0 by default.  Do you think there's any reason why we shouldn't just use what Storybook uses and set the target as ES2015?

**Comment by IanVS** [comment]
I'm not sure we need to go that far back.  Replicating the node12 config might work well, though, eh? 
 https://github.com/tsconfig/bases/blob/main/bases/node12.json

**Comment by joshwooding** [comment]
Yeah, that should be enough. I think node12 support is as low as we should go.
