### ISSUE TITLE
Infinite Loading when using Storybook with Vite 

### ISSUE THREAD

**Issue by MatheusMoselli** [eirslett/storybook-builder-vite#270]
I already used Storybook with CRA, and it worked fine, but when I try to use when Vite it get stuck in infinite loading. The project runs without problems with the command _npm run storybook_, but nothing appears on the screen.

I'm using a React-App with typescript

I think the error has something to do with the module.exports in the storybook file, since I can't use module.exports for **.eslint.js**
![image](https://user-images.githubusercontent.com/93735046/156815841-c89b7483-4285-4cfa-bc54-6e487ca4697d.png)

PS: There is an error in the console, too.
![image](https://user-images.githubusercontent.com/93735046/156815907-9998b443-659b-4032-a877-8833ebe1f15c.png)

**Comment by IanVS** [comment]
@MatheusMoselli thanks for reporting this.  It seems to be coming from the manager (webpack) portion of storybook.  Are you able to share a reproduction by any chance, so that I can look into it?

**Comment by MatheusMoselli** [comment]
Of course! Sorry for the late reply, I was a little busy.
But here it goes:
https://github.com/MatheusMoselli/storybook-vite

**Comment by lgarest** [comment]
I had the same issue with the infinite loading screen but a different error in the console about `Uncaught SyntaxError: import not found: ModuleMocker`
![screenshot](https://i.imgur.com/6054Msr.png)
I could fix it with https://github.com/eirslett/storybook-builder-vite/issues/242#issuecomment-1044262283

**Comment by MatheusMoselli** [comment]
Yeah, this is is the error that appears when I open the storybook in the firefox.
The workaround worked thanks 🚀
