### ISSUE TITLE
Files not found when exposed using domain subfolder

### ISSUE THREAD

**Issue by smarlhens** [eirslett/storybook-builder-vite#271]
Hey all 👋🏻 ,

I am trying to serve (using `start-storybook`) my storybook using `https://domain.tld:port/storybook/` (**as base url**) and when I'm looking at the browser network tab I'm getting a `404` error on the following URIs :
-  `/virtual:/@storybook/builder-vite/vite-app.js`. 
- `/progress`

I see that both URIs are starting `/`, defined in (I guess) 
- [input/iframe.html](https://github.com/eirslett/storybook-builder-vite/blob/bfc38e9bfd1691d660d7d7255ab6d488e36f8ae9/packages/storybook-builder-vite/input/iframe.html#L35) line 35: 
```html
<script type="module" src="/virtual:/@storybook/builder-vite/vite-app.js"></script>
```
- [index.ts](https://github.com/eirslett/storybook-builder-vite/blob/22a38e2f85d1cbc2b583ae6e8a7e0c2f7ecea07e/packages/storybook-builder-vite/index.ts#L37) line 37:
```typescript
router.get('/progress', (req: Request, res: Response) => {
```

Can it be the root cause of my problem ? 
I haven't found how to do it from the documentation, I'll be happy to get any help 🙏🏻 

Thanks in advance, wish you a nice day ☀️ 

PS: I apologize if the subject already has an open issue and I did not see it.

**Comment by IanVS** [comment]
Hi, you can use the 'base' config param of vite to fix this.  See https://github.com/eirslett/storybook-builder-vite/issues/238 for an example.

**Comment by smarlhens** [comment]
@IanVS Hi ! I apologize for the delay of response.
It works fine, thanks 🙏🏻 
```js
  viteFinal(config) {
    return {
      ...config,
      base: '/storybook/',
    };
  },
```
