### ISSUE TITLE
MDX/addon-docs cannot use ArgsTable, Canvas

### ISSUE THREAD

**Issue by przemuh** [eirslett/storybook-builder-vite#279]
`Canvas` and `ArgsTable` don't work in mdx stories.

Versions of packages:

```
    "@babel/core": "^7.17.7",
    "@storybook/addon-actions": "^6.5.0-alpha.48",
    "@storybook/addon-essentials": "^6.5.0-alpha.48",
    "@storybook/addon-interactions": "^6.5.0-alpha.48",
    "@storybook/addon-links": "^6.5.0-alpha.48",
    "@storybook/react": "^6.5.0-alpha.48",
    "@storybook/testing-library": "^0.0.9",
    "@types/react": "^17.0.33",
    "@types/react-dom": "^17.0.10",
    "@vitejs/plugin-react": "^1.0.7",
    "babel-loader": "^8.2.3",
    "storybook-builder-vite": "^0.1.20",
    "typescript": "^4.5.4",
    "vite": "^2.8.0"
 ```

Steps to reproduce:

- init vite project and storybook-vite builder (standard way)

```
npm create vite my-project --template react-ts
cd my-project
npx sb@next init --builder storybook-builder-vite
```

- try to add following code to the `Introduction.stories.mdx`

```
import { Meta, ArgsTable } from "@storybook/addon-docs";

import { Button } from "./Button";

<Meta title="Example/Introduction" />

<Canvas>
  <Button label="aaa" />
</Canvas>

<ArgsTable of={Button} />
```

Actual result:

Empty docs page + console.error:

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/3865478/158618343-2b687f52-d726-4952-bfde-72c323fae97c.png">

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/3865478/158619269-ac27be76-92a3-4908-91aa-04c285e2046f.png">

**Comment by IanVS** [comment]
@przemuh did you find a solution?

**Comment by a33068843** [comment]
You need to import `Canvas` and `Story`.

And add `Story` in `Introduction.stories.mdx` 

### Like
```jsx
import { Meta, Canvas, Story, ArgsTable } from "@storybook/addon-docs";

import { Button } from "./Button";

<Meta title="Example/Introduction" />

<Canvas>
  <Story name="Button">
    <Button label="aaa" />
  </Story>
</Canvas> // Why this line is not orange :(

<ArgsTable of={Button} />
```

### Image
![image](https://user-images.githubusercontent.com/31796210/158711142-fba21b24-a020-4864-83a5-59dd7d1f689b.png)

### Problem
But I can't show Docs by doing so.

( And `ArgsTable` is not working, either.)

**Comment by IanVS** [comment]
>But I can't show Docs by doing so.

Yes, when you write an MDX story, that is treated as `Docs`.  The automatic Docs tab is for CSF stories, for when you don't want to write your own custom MDX docs.

>And ArgsTable is not working, either.

I'm guessing that's related to https://github.com/eirslett/storybook-builder-vite/issues/103, but I haven't dug into how the ArgsTable actually works.  I'd love to review a PR from anyone who does dig in, though!
