### ISSUE TITLE
storybook addons interaction bug

### ISSUE THREAD

**Issue by Abdelatief** [eirslett/storybook-builder-vite#283]
upon adding storybook to the react ts template storybook doesn't load stories, when I removed the storybook interactions add on it worked just fine.

**Comment by THATBLADEBOY** [comment]
@Abdelatief Thanks for posting this issue! I had the same problem. Received a 404 error. Curious how you figured out that the interactions add on was the issue?

**Comment by IanVS** [comment]
Hi, could this be what you are experiencing? https://github.com/eirslett/storybook-builder-vite/issues/186

**Comment by Abdelatief** [comment]
> @Abdelatief Thanks for posting this issue! I had the same problem. Received a 404 error. Curious how you figured out that the interactions add on was the issue?

**Comment by Abdelatief** [comment]
> Hi, could this be what you are experiencing? #186

I am not using @storybook/jest but thanks

**Comment by Abdelatief** [comment]
> @Abdelatief Thanks for posting this issue! I had the same problem. Received a 404 error. Curious how you figured out that the interactions add on was the issue?

just trial and error, I was messing with storybook configurations and removed all the add ons and it worked fine then I added them one by one to find that the problem in the interactions add on

**Comment by IanVS** [comment]
@storybook/jest is included in the interactions addon.  Can you post the error you're seeing?

**Comment by Abdelatief** [comment]
> @storybook/jest is included in the interactions addon. Can you post the error you're seeing?

there are no errors. storybook loader keeps showing and no stories are loaded, also I will check the issue you linked then

**Comment by Abdelatief** [comment]
> @storybook/jest is included in the interactions addon. Can you post the error you're seeing?

I found this message in the browser's console
Uncaught ReferenceError: global is not defined

**Comment by Abdelatief** [comment]
> The `render was not supported :(` message is harmless, although it sounds scary.
> 
> ```
> Uncaught ReferenceError: global is not defined
> ```
> 
> ^ indicates that this is indeed due to the issue I linked. Until we find a better way to solve it, you can create a `.storybook/preview-head.html` with contents of:
> 
> ```
> <script>
>   window.global = window;
> </script>
> ```

thanks a lot it works fine now
