### ISSUE TITLE
No docs.container on docs tab on clean setup

### ISSUE THREAD

**Issue by webdesignberlin** [eirslett/storybook-builder-vite#285]
clean setup ends in error calling docs.

**Steps to reproduce:**
get https://github.com/webdesignberlin/sb-builder-vite-no-container or:

Node 16
`npm init vue@latest`
```
✔ Project name: … latest-test
✔ Add TypeScript? … Yes
✔ Add JSX Support? … No
✔ Add Vue Router for Single Page Application development? … No
✔ Add Pinia for state management? … No
✔ Add Vitest for Unit Testing? … Yes
✔ Add Cypress for End-to-End testing? … Yes
✔ Add ESLint for code quality? … Yes
✔ Add Prettier for code formatting? … No
```
`npm install`
Run SB init:
`npx sb@next init --builder storybook-builder-vite`
Run Storybook:
`npm run storybook`
go to some docs page get following
Error:
`
Uncaught (in promise) Error: No `docs.container` set, did you run `addon-docs/preset`?
    at _callee$ (renderDocs-LVJGRNMN.js:110:19)
    at tryCatch (:6007/node_modules/.vite-storybook/chunk-2ZKQNBD4.js?v=506d2ae8:45:44)
    at Generator.invoke [as _invoke] (:6007/node_modules/.vite-storybook/chunk-2ZKQNBD4.js?v=506d2ae8:182:26)
    at Generator.next (:6007/node_modules/.vite-storybook/chunk-2ZKQNBD4.js?v=506d2ae8:78:25)
    at asyncGeneratorStep (renderDocs-LVJGRNMN.js:64:24)
    at _next (renderDocs-LVJGRNMN.js:82:9)
    at renderDocs-LVJGRNMN.js:87:7
    at new Promise (<anonymous>)
    at renderDocs-LVJGRNMN.js:79:12
    at _renderDocsAsync (renderDocs-LVJGRNMN.js:166:27)
renderDocs.js:39 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'container')
    at _callee$ (renderDocs.js:39:32)
    at tryCatch (runtime.js:63:40)
    at Generator.invoke [as _invoke] (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at asyncGeneratorStep (renderDocs.js:5:99)
    at _next (renderDocs.js:7:194)
    at renderDocs.js:7:364
    at new Promise (<anonymous>)
    at renderDocs.js:7:97
    at renderDocsAsync (renderDocs.js:17:27)
_callee$ @ renderDocs.js:39
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonym) @ runtime.js:119
asyncGeneratorStep @ renderDocs.js:5
_next @ renderDocs.js:7
(anonym) @ renderDocs.js:7
(anonym) @ renderDocs.js:7
renderDocsAsync @ renderDocs.js:17
renderDocs @ renderDocs.js:13
_callee2$ @ DocsRender.js:127
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonym) @ runtime.js:119
asyncGeneratorStep @ DocsRender.js:7
_next @ DocsRender.js:9
Promise.then (async)
renderDocs @ renderDocs.js:13
_callee2$ @ DocsRender.js:127
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonym) @ runtime.js:119
asyncGeneratorStep @ DocsRender.js:7
_next @ DocsRender.js:9
Promise.then (async)
asyncGeneratorStep @ DocsRender.js:7
_next @ DocsRender.js:9
(anonym) @ DocsRender.js:9
(anonym) @ DocsRender.js:9
render @ DocsRender.js:140
_callee$ @ DocsRender.js:87
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonym) @ runtime.js:119
asyncGeneratorStep @ DocsRender.js:7
_next @ DocsRender.js:9
Promise.then (async)
asyncGeneratorStep @ DocsRender.js:7
_next @ DocsRender.js:9
(anonym) @ DocsRender.js:9
(anonym) @ DocsRender.js:9
renderToElement @ DocsRender.js:98
_callee12$ @ PreviewWeb.js:934
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonym) @ runtime.js:119
asyncGeneratorStep3 @ PreviewWeb.js:8
_next @ PreviewWeb.js:10
Promise.then (async)
asyncGeneratorStep3 @ PreviewWeb.js:8
_next @ PreviewWeb.js:10
Promise.then (async)
asyncGeneratorStep3 @ PreviewWeb.js:8
_next @ PreviewWeb.js:10
(anonym) @ PreviewWeb.js:10
(anonym) @ PreviewWeb.js:10
renderSelection @ PreviewWeb.js:949
onSetCurrentStory @ PreviewWeb.js:560
(anonym) @ index.js:168
handleEvent @ index.js:167
(anonym) @ index.js:52
handler @ index.js:101
handleEvent @ index.js:286
postMessage (async)
(anonym) @ main.f1159ece7311d200d210.manager.bundle.js:2
send @ main.f1159ece7311d200d210.manager.bundle.js:2
handler @ main.f1159ece7311d200d210.manager.bundle.js:2
emit @ main.f1159ece7311d200d210.manager.bundle.js:2
emit @ main.f1159ece7311d200d210.manager.bundle.js:2
(anonym) @ main.f1159ece7311d200d210.manager.bundle.js:2
Ii @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
Vj @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
exports.unstable_runWithPriority @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
cg @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
Dj @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
yj @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
(anonym) @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
exports.unstable_runWithPriority @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
cg @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
fg @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
gg @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
Ga @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
gd @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
`

**Comment by IanVS** [comment]
It looks like you are missing `@storybook/addon-docs` in your list of addons: https://github.com/webdesignberlin/sb-builder-vite-no-container/blob/341e085d9ad2bc644a68e3769311c9c8310bedd2/.storybook/main.js#L6

**Comment by webdesignberlin** [comment]
If i add @storybook/addon-docs in main.js, i get the hint that will be skipped.
both, without manually adding to the package.json, as well as with manual adding to package.json

`info => Loading presets
info Found existing addon "@storybook/addon-docs", skipping.
`

**Comment by webdesignberlin** [comment]
thx for help. hmmm, i have no success with 6.5.0-alpha.47. steps to reproduce:

node 16.13.0
`npm init vue@latest `
```
✔ Project name: … aplha47
✔ Add TypeScript? … No / Yes
✔ Add JSX Support? … No / Yes
✔ Add Vue Router for Single Page Application development? … No / Yes
✔ Add Pinia for state management? … No / Yes
✔ Add Vitest for Unit Testing? … No / Yes
✔ Add Cypress for End-to-End testing? … No / Yes
✔ Add ESLint for code quality? … No / Yes
✔ Add Prettier for code formatting? … No / Yes
```
`npx sb@6.5.0-alpha.47 init --builder storybook-builder-vite `
`npm run storybook `

**Comment by webdesignberlin** [comment]
okay. i can confirm that it works with version 6.5.0-alpha.47. I create an issue in the storybook repo. many thanks!
