### ISSUE TITLE
Help wanted: React HMR is not working properly when making changes to stories

### ISSUE THREAD

**Issue by eirslett** [eirslett/storybook-builder-vite#3]

**Comment by tjlittle** [comment]
HMR doesn't seem to be working for Svelte either... changes to both stories and components do not result in any page updates

**Comment by productfrontenddeveloper** [comment]
+1

**Comment by hanayashiki** [comment]
Same problem here, not a big problem with vite, but it hurts...

**Comment by IanVS** [comment]
@tjlittle I've opened https://github.com/eirslett/storybook-builder-vite/issues/52 to track the svelte HMR issue.

**Comment by IanVS** [comment]
Interesting, it seems like changes to `.stories` files are not HMRed either in the webpack builder: https://github.com/storybookjs/storybook/issues/12626#issuecomment-753926138
