### ISSUE TITLE
Error when using resolver.alias

### ISSUE THREAD

**Issue by imdongchen** [eirslett/storybook-builder-vite#30]
With 

```
 config.resolve.alias = { 'components': '/src/components' }
```
Storybook is requesting a file like `localhost:8000/src/components/...`, but it seems only `localhost:8000/@fs/Users/dongchen/path/to/src/components/...` (@fs + absolute path) would work. Can you provide an example how to do alias?

**Comment by julrich** [comment]
Seems like it could, maybe, be related to https://github.com/eirslett/storybook-builder-vite/pull/28?

**Comment by eirslett** [comment]
Try using `./src/components` (dot first)?

**Comment by eirslett** [comment]
Or `'components': path.resolve(__dirname, 'src', 'components')`

**Comment by soulsam480** [comment]
Hii guys, just got into this issue. I have my `src` directory as a `tsconfig` path.

**Comment by imdongchen** [comment]
With `./src/components` the request becomes `localhost:8000/@id/src/suspense/Suspense` (where is `@id` generated from?) 

With `path.resolve(__dirname, 'src', 'components')`, request becomes `localhost:8000/Users/dongchen/path/to/src/components/...` (path is right but missing the `@fs`)

**Comment by soulsam480** [comment]
I'm looking into this issue. I'm doing it on a react-ts project.

**Comment by eirslett** [comment]
@imdongchen Maybe you're hit by the `fsServe.strict` setting that is enabled by default? You could try turning it off and see if that helps - or configuring the `root` directory?

**Comment by imdongchen** [comment]
Turning off `fsServe.strict` works! Thanks!

**Comment by eirslett** [comment]
> Turning off fsServe.strict works! Thanks!

But ideally, I would suggest that you re-enable the setting, and try to configure fsServe.root properly so that it still serves your stories!
