### ISSUE TITLE
Custom vite plugin not working

### ISSUE THREAD

**Issue by c10b10** [eirslett/storybook-builder-vite#33]
I'm trying to install the [`vite-plugin-react-svg` plugin](https://github.com/kanweiwei/vite-plugin-react-svg/) in a react storybook app and it doesn't seem to work.

I've tried adding the plugin both to `vite.config.js` and to `.storybook/main.js`'s `viteFinal` and nothing seems to have changed.

Any ideas how could I debug / solve this issue?

**Comment by IanVS** [comment]
Does the plugin work correctly in your app when you start it up without storybook?  Could you share your `viteFinal`, and any other details on what you expect to happen vs what is actually happening?

**Comment by c10b10** [comment]
What I expect is that when I import a svg file with:

```
import { ReactComponent } from './path/to/file.svg';
```

I get a React svg component instead of `undefined` in the case of the named import from above, or  './path/to/file.svg' in the case of default import.

I couldn't find a way to debug if the plugin is even loaded, but the system behaves as if it is not.
I can't start the app without storybook because it's a component library embedded in storybook.

`vite.config.js`

```
import { defineConfig } from "vite";
import reactRefresh from "@vitejs/plugin-react-refresh";
import svgPlugin from "vite-plugin-react-svg";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svgPlugin(), reactRefresh()],
});
```

`.storybook/main.js`

```
const reactRefresh = require("@vitejs/plugin-react-refresh");
const svgPlugin = require("vite-plugin-react-svg");

module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-a11y",
    "@storybook/addon-actions",
    "@storybook/addon-docs",
    "@storybook/addon-essentials",
    "@storybook/addon-links",
    "@storybook/addon-storysource",
    "storybook-styled-components-theme-selector",
    // "@storybook/preset-create-react-app",
  ],
  core: {
    builder: "storybook-builder-vite",
    async viteFinal(config, { configType }) {
      return {
        ...config,
        plugins: [svgPlugin(), reactRefresh()],
      };
    },
  },
};
```

Output of `npx envinfo --system --npmPackages vite,@vitejs/plugin-react-refresh,storybook-builder-vite,vite-plugin-react-svg --binaries --browsers`:

```
  System:
    OS: macOS 11.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.00 GB / 32.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.20.2 - ~/.nvm/versions/node/v12.20.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.20.2/bin/npm
  Browsers:
    Chrome: 91.0.4472.106
    Firefox: 89.0
    Safari: 14.1
  npmPackages:
    @vitejs/plugin-react-refresh: ^1.3.1 => 1.3.3
    storybook-builder-vite: ^0.0.9 => 0.0.9
    vite: ^2.3.7 => 2.3.7
    vite-plugin-react-svg: ^0.2.0 => 0.2.0
```

**Comment by schalk-b** [comment]
Just an observation, instead of:
`plugins: [svgPlugin(), reactRefresh()],` you should use `plugins: [...config.plugins, svgPlugin(), reactRefresh()],`

Otherwise you override the default plugins configuration

**Comment by eirslett** [comment]
I believe @schalk-b's suggestion should work. If not, then reopen the issue!

**Comment by neilchaudhuri** [comment]
I have a similar issue. Given my plugin configuration in `viteFinal`:

```
viteFinal: async config => {
		return {
			...config,
			plugins: [...config.plugins, svgPlugin()],
		}
},
```

I'm getting 

``
Failed to execute 'createElement' on 'Document': The tag name provided ('/assets/seal.svg') is not a valid name.
``

As if the plugin isn't even "active."

Any hints on what I am doing wrong in my configuration?

Meanwhile, I don't have any SVG-related config in my `config.vite.ts`to refer to  because I am building a component library where one component takes an SVG as one of its props. It's only in the story where I am demonstrating its use. 

Any ideas are appreciated.

**Comment by benglewis** [comment]
I just tried this with `@svgr/rollup` and `vite-plugin-svgr` and it also isn't working for me :'(

**Comment by IanVS** [comment]
@benglewis can you please open a new issue with all the details so we can help?
