### ISSUE TITLE
Failing to start with Vue 

### ISSUE THREAD

**Issue by husayt** [eirslett/storybook-builder-vite#35]
I get this error on running storybook:

`Failed to load resource: the server responded with a status of 404 (Not Found)`

![image](https://user-images.githubusercontent.com/1169324/122600153-48694700-d067-11eb-8116-678dc8bc1f53.png)

**Comment by eirslett** [comment]
Maybe you need to force refresh your web browser? It could be cache related.

**Comment by husayt** [comment]
İ wish it was, but it is not refresh issue and I don't get any other error

**Comment by eirslett** [comment]
Anything in the logs? Are you able to make a reproducible minimum example?

**Comment by husayt** [comment]
when I do build I get, this error:
`SyntaxError: Unexpected token (2:2)`:
`component.js[rollup-plugin-dynamic-import-variables] Unexpected token (2:2)`

I just tried testing this on [Vitesse template by antfy](https://github.com/antfu/vitesse). Got the template and installed this plugin there with `npx sb@next init --builder storybook-builder-vite`. 
I just then updated `main.js` to include dependencies. That is it.

This is the main.js:

```
const VueI18n = require("@intlify/vite-plugin-vue-i18n").default
const WindiCSS = require("vite-plugin-windicss").default
const ViteComponents = require("vite-plugin-components").default
const ViteIcons = require("vite-plugin-icons").default
const Pages = require("vite-plugin-pages").default
const { HeadlessUiResolver } = require("vite-plugin-components")
const { ViteIconsResolver } = require("vite-plugin-icons")
const  Layouts=require('vite-plugin-vue-layouts').default
const {VitePWA}=require('vite-plugin-pwa')
const Vue=require('@vitejs/plugin-vue').default

const path = require("path")

const viteConfig = {
  plugins: [
    Vue({
      include: [/\.vue$/, /\.md$/],
    }),

    // https://github.com/JohnCampionJr/vite-plugin-vue-layouts
    Layouts(),

    // https://github.com/antfu/vite-plugin-windicss
    WindiCSS({
      safelist: "prose prose-sm m-auto",
    }),

    // https://github.com/intlify/vite-plugin-vue-i18n
    VueI18n({
      include: path.resolve(__dirname, "../locales/**"),
    }),

    // https://github.com/hannoeru/vite-plugin-pages
    Pages({
      extensions: ["vue", "md"],
      routeBlockLang: "yaml",

    }),
    VitePWA({})
  ],

}

module.exports = {
  async viteFinal(config, { configType }) {
    Object.assign(config, viteConfig)

    // return the customized config
    return config
  },
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ],
  "core": {
    "builder": "storybook-builder-vite"
  }
}
```

It's Typescript project I run on windows. 
I will try to get an example for you, but thought maybe someone has stumbled on this before.

It will be great to have this tested and working on one of more realistic templates available, that would help a lot with adoption. Thank you for making this possible.

**Comment by IanVS** [comment]
What framework are you using?  You will probably want to spread the default config's plugins into yours.  @eirslett I think this will be a common problem, we might want to update the docs to make it clear.

Also, I see your file is named `component.js`.  If it happens to contain jsx, it will need to end with `.jsx` or `.tsx`. That is a requirement from vite.

**Comment by husayt** [comment]
Ian, as mentioned above this is exactly what I am trying with:

https://github.com/antfu/vitesse

İ just install and run storybook on top of that following the instructions. 

Also, yes, in the code above I am merging local and provided config with

`Object.assign(config, viteConfig)`


Vitesse is a pretty popular vite & vue template. It is a good real app example to get storybook working with. If this can be done it will be a really good example for everyone

**Comment by IanVS** [comment]
`Object.assign` only does a shallow merge, so your `plugins` will completely replace the `plugins` of `config`.  I searched in `vitesse` for `component.js` and couldn't find it.  If you could give us a link to a reproduction, we can try to troubleshoot further.

**Comment by husayt** [comment]
@IanVS you were spot on, I completely missed about shallow merge effect of object.assign. That basically was the missing bit.
It works now. Thank you very much

**Comment by blowsie** [comment]
@husayt could you be so kind to share your working config?
