### ISSUE TITLE
`app.use`

### ISSUE THREAD

**Issue by husayt** [eirslett/storybook-builder-vite#36]
I would normally register `Vue Router` or `i18n` in Vue3 with `app.use` e.g.
```
app.use(i18n)
```

But I don't see how to get hold of it here.

Is there any example or any tip on this?

Thanks in advance

**Comment by eirslett** [comment]
Unfortunately, the Storybook Builder API doesn't expose the dev server all the way out into userland (as far as I know of...) so there's no simple way to do it. You might have to write your own dev server, but I'm not not sure if that's even possible with Storybook...
Why do you need Vue Router inside Storybook?

**Comment by shilman** [comment]
I don't think this is a vite question.

https://github.com/storybookjs/storybook/tree/next/app/vue3#extending-the-vue-application

**Comment by husayt** [comment]
@shilman Thank you. This is what I was after.
