### ISSUE TITLE
The requested module does not provide an export named 'default'

### ISSUE THREAD

**Issue by JesusTheHun** [eirslett/storybook-builder-vite#37]
Switching from the regular builder, I removed storybook from my project and re-installed it using 

`npx sb@next init --builder storybook-builder-vite`

<details>
<summary>.storybook/main.js</summary>
module.exports = {
  core: { builder: "storybook-builder-vite" },
  async viteFinal(config, { configType }) {
    // customize the Vite config here
    config.resolve.alias = { ...config.resolve.alias, ...absolutePathAliases };

    // return the customized config
    return config;
  },
  stories: [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  addons: [
    "@storybook/addon-actions",
    "@storybook/addon-essentials",
    "storybook-addon-intl",
    {
      name: '@storybook/addon-postcss',
      options: {
        postcssLoaderOptions: {
          implementation: require('postcss'),
        },
      },
    },
  ],
  typescript: {
    check: false,
    checkOptions: {},
    reactDocgen: 'react-docgen-typescript',
  },
}

</details>

When starting storybook I have no error, but when I open storybook in the browser I get this error : 

`Uncaught SyntaxError: The requested module '/node_modules/hoist-non-react-statics/dist/hoist-non-react-statics.cjs.js?v=403370d2' does not provide an export named 'default'` coming from `emotion-theming.browser.esm.js?v=403370d2`

I'm not sure if this issue is related to this repo directly but I have to start somewhere :)

**Comment by eirslett** [comment]
Have you tried adding the problematic dependencies to optimizeDeps?

**Comment by JesusTheHun** [comment]
Adding `@emotion/react` to `optimizeDeps` solves the issue

**Comment by akbarik** [comment]
Adding `@emotion/react` to `optimizeDeps` didn't help in my case

**Comment by IanVS** [comment]
Do you see any messages in your terminal about vite finding new dependencies?

**Comment by akbarik** [comment]
Yes @IanVS , there is one actually:
```
[vite] new dependencies found: @emotion/react/jsx-dev-runtime, updating...
```
What should I do with that?

**Comment by IanVS** [comment]
@akbarik, that also needs to be added to your `optimizeDeps.include`.  Storybook doesn't like it when Vite finds new deps and updates.  Not sure exactly why, but making sure you don't have any of those messages is important for the storybook vite builder to work correctly.

**Comment by akbarik** [comment]
Damn, now this error happens when I open Storybook ((
When launching Storybook I received new dependencies messages in the console and so I added all of those to `optimizeDeps.include` list of `viteFinal`'s entry of the configuration in `.storybook/main.js`. After that there were no new deps messages in the console any more. But when opening Storybook in the browser's console I receive this error:
```
SyntaxError: The requested module '/node_modules/hoist-non-react-statics/dist/hoist-non-react-statics.cjs.js?v=236b7c74' does not provide an export named 'default'
```
This error is referring to `node_modules/emotion-theming/dist/emotion-theming.browser.esm.js?v=236b7c74` file.
Can someone please tell me what can be done in this case?

**Comment by IanVS** [comment]
@akbarik is it possible for you to share a link to your project?  I believe you should be able to add `hoist-non-react-statics` to your optimizeDeps.include.  Also, be sure not to override the existing `optimizeDeps.entries` and `optimizeDeps.include` in the initial config that is provided as a param to the `viteFinal` function.  

Why do you say the error refers to `emotion-theming.browser.esm.js?v=236b7c74`?  I don't see that referenced in what you included.  But, if that is also causing errors, you should be able to include `emotion-theming` in the list, right?

**Comment by akbarik** [comment]
You're right, the problem was with overwriting the existing `optimizeDeps`. Thanks!

**Comment by stephenhebert** [comment]
This thread saved my day today.  Thank you!

**Comment by AbednegoTM** [comment]
Thread helped me thanks everyone

**Comment by leah-committed** [comment]
Where to add @emotion/react ?

export default defineConfig({
  plugins: [react()],
  server: {
    host: 'localhost',
    port: 4852,
  },optimizeDeps: {
    exclude: ['js-big-decimal']
  }
});
