### ISSUE TITLE
Support legacy storiesOf

### ISSUE THREAD

**Issue by thebuilder** [eirslett/storybook-builder-vite#39]
Trying to convert from Webpack to Vite, I'm seeing this error:

```
Uncaught Error: Cannot add an argTypes enhancer to the store after a story has been added.
    at StoryStore2.addArgTypesEnhancer3 (story_store.js:536)
    at ClientApi2.addArgTypesEnhancer (client_api.js:132)
    at addArgTypesEnhancer2 (client_api.js:72)
    at vite-app.js:61
```

It's caused by having a `storiesOf` entry in a story file.

```js
import React from 'react';
import { storiesOf } from '@storybook/react';

storiesOf('Dynamic', module).add('Story', () => <div>Test</div>);
```

I'm guessing it's because `module` is `undefined` in the Vite context, but not sure what (if anything) to replace it with.

While it is a legacy API, it is also still the only way to add a dynamic list of stories (something that fits perfectly with `import.meta.globEager`).

**Comment by eirslett** [comment]
I don't think it's possible. `module` doesn't exist in an ESM context. Maybe something like `import.meta`? @shilman should there be a way to support this?

**Comment by shilman** [comment]
There's a good chance we'll remove storiesOf support in 7.0 -- CSF will have been out for over two years -- and we're starting to release features that depend on CSF.

In short, I probably wouldn't prioritize this one.

**Comment by thebuilder** [comment]
@shilman there still isn't a way of dynamically creating stories using CSF? It is a nicer API, but we like to use it to dynamically include a `glob` of components/pages, as a way of ensuring we always include all components.

I can get around it, but I'll have to create a story file for each component manually (or with a generator).

**Comment by shilman** [comment]
For CSF we support globs for the name of the story files, but within the file the stories must able to be statically analyzed. I have a strawman for how to implement combinatorial tests in this way. But something simple like "create a story for every component" which would be pretty easy in storiesOf requires manual work in CSF (or implementing a webpack loader--does vite have a similar concept?).
