### ISSUE TITLE
main.ts typescript not working

### ISSUE THREAD

**Issue by schalk-b** [eirslett/storybook-builder-vite#43]
On a fresh project:

Rename: `.storybook/main.js` to `.storybook/main.ts`
Change the content to:
```typescript
let myVar: string = 'test'
console.log(myVar)

module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ],
  "core": {
    "builder": "storybook-builder-vite"
  }
}
```

Run
`npm run storybook`

Outputs:
```
ERR! SyntaxError: <repo path>\.storybook\main.ts: Missing semicolon. (1:9)
ERR!
ERR! > 1 | let myVar: string = 'test'
ERR!     |          ^
ERR!   2 | console.log(myVar)
```

**Comment by IanVS** [comment]
Does that work with the webpack builder?  I guess I've always assumed that the config file needed to be plain commonjs.

**Comment by schalk-b** [comment]
Yes, there are typescript examples in the storybooks example folder: https://github.com/storybookjs/storybook/blob/next/examples/react-ts-webpack4/main.ts

My use case is that I have several custom vite plugins developed in typescript, it would make my life easier if I could include those plugins in the same way that I include them in vite.config.ts

**Comment by schalk-b** [comment]
I have a workaround for this:

```
npm install -D ts-node
npm install -D cross-env
```

create:
`tsconfig.storybook.json`
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "CommonJS",
  },
  "include": [".storybook/**/*.ts"],
}
```

Update `package.json`
`"storybook": "cross-env TS_NODE_PROJECT=tsconfig.storybook.json start-storybook -p 6006",`
