### ISSUE TITLE
codeSource doesn't work

### ISSUE THREAD

**Issue by Flo2315** [eirslett/storybook-builder-vite#44]
Hi 👋

It is impossible to show the source code of the component (vue 3).
<img width="1511" alt="Capture d’écran 2021-06-24 à 17 46 26" src="https://user-images.githubusercontent.com/7684148/123242397-93c2a000-d514-11eb-894f-f10ae531e654.png">

any idea why this is not working?

```
npm init @vitejs/app my-vite-app
npx sb@next init --builder storybook-builder-vite
npm run storybook

```
Thx

**Comment by eirslett** [comment]
I have seen this problem with React too. Might be related to #40.

**Comment by eirslett** [comment]
@Flo2315 Can you try again with the latest version of the builder, latest version of Storybook and latest version of Vite?

**Comment by yzy8366** [comment]
doesn't work

**Comment by yzy8366** [comment]
![image](https://user-images.githubusercontent.com/23303336/126103544-b7bebac8-5364-4afe-9711-2b45b6ac7597.png)
use 6.4.0-alpha.18

**Comment by eirslett** [comment]
Ok so it works with Storybook 6.4 alpha? (Maybe also with Storybook 6.3.4 or newer?)

**Comment by yzy8366** [comment]
6.3.4 doesn't work
6.4.0-alpha.18 work

**Comment by eirslett** [comment]
Ok, I suggest we wait for Storybook 6.4 then! (Or suggest that people use the alpha version). Since it works there, I think the problem is in Storybook and not in the Vite builder.

**Comment by ladislas14** [comment]
Hi,

I'm using Storybook 6.4.0-alpha.33 with Vite loader and it is impossible to show source code.

Do you face the same issue with alpha.33 ?
