### ISSUE TITLE
config.build.target isn't working

### ISSUE THREAD

**Issue by mitow7821** [eirslett/storybook-builder-vite#48]
I'am using `async viteFinal(config, { configType }) {
    config.build.target = ""; return config }` 
but if I try run storybook this error shows:

![image](https://user-images.githubusercontent.com/34492112/123869413-3e7df880-d931-11eb-95e7-227dca6f158e.png)
so I've changed config to `  config.build = {};
    config.build.target = "";` and error disapear, but when i try to deploy stories with chromatic I am getting error because of this two lines (first config works fine in this case)

How to define `build.target` in config to make it work properly?

**Comment by eirslett** [comment]
This is a problem with Vite, I guess - did you configure your target environment, or did you stick with the defaults?

**Comment by mitow7821** [comment]
I've change build.target to empty string and error is gone, but next one appears: 
![image](https://user-images.githubusercontent.com/34492112/123511085-98f02e00-d67f-11eb-9ac4-8ca8c35729f2.png)

**Comment by mitow7821** [comment]
I'am using `async viteFinal(config, { configType }) {
    config.build.target = ""; return config }` 
but if I try run storybook this error shows:

![image](https://user-images.githubusercontent.com/34492112/123869413-3e7df880-d931-11eb-95e7-227dca6f158e.png)
so I've changed config to `  config.build = {};
    config.build.target = "";` and error disapear, but when i try to deploy stories with chromatic I am getting error because of this two lines (first config works fine in this case)

How to define `build.target` in config to make it work properly?
