### ISSUE TITLE
Support vite 2.4

### ISSUE THREAD

**Issue by IanVS** [eirslett/storybook-builder-vite#59]
There are some [breaking changes](https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md#breaking-changes) in the way that file serving boundaries are secured, which we will need to update our config to handle.  Since we don't control the version of vite that is being used, we may also need to support both config options.

**Comment by eirslett** [comment]
> Since we don't control the version of vite that is being used, we may also need to support both config options.

We can control it, kind of. We can make storybook-builder-vite only support Vite version 2.4+ from now on.

**Comment by schalk-b** [comment]
I agree, I think it's better to just support Vite 2.4+. This library is still experimental, I don't think people will be too surprised.

**Comment by eirslett** [comment]
Fixed in the latest release.
