### ISSUE TITLE
Support for monorepos

### ISSUE THREAD

**Issue by jamesg1** [eirslett/storybook-builder-vite#60]
Firstly excellent library vite and esbuild has been a blessing to improve load dev performance.

I was trying to see if it was possible to use this plugin in a monorepo environment (eg npm7 worksapces or yarn).

From what I understand traditionally in webpack 4 the storybook config goes to the root of the project and then a wildcard resolve is provided - I found this great blog describing this - https://kamranicus.com/using-storybook-in-a-monorepo/

I guess its also not a big deal to just run storybook within a package within the monorepo rather than the root of the project.

**Comment by eirslett** [comment]
It should be possible - if you look at this github repository, it's actually a monorepo environment with different "example" packages where each package has its own storybook.

**Comment by jamesg1** [comment]
I was more asking around being able to have storybook at the root of the project which is how existing webpack Configs can work.

**Comment by eirslett** [comment]
I'm not sure, I haven't tried. Can you give it a go, and see how it works?
