### ISSUE TITLE
esbuild_1.startService is not a function

### ISSUE THREAD

**Issue by timgoeller** [eirslett/storybook-builder-vite#63]
We're currently getting this error for each component, when using `storybook-builder-vite`:

<img width="972" alt="Bildschirmfoto 2021-07-06 um 08 28 21" src="https://user-images.githubusercontent.com/10633973/124553089-9a1a1b80-de34-11eb-8656-9bb5e1ea1042.png">

It's a Vue project using vite 2.4.0. 
I _guess_ it's because https://github.com/brillout/vite-plugin-mdx does not seem to support Vue yet, but I'm not 100% sure about that.

**Comment by eirslett** [comment]
@timgoeller Did you find a solution to this?

**Comment by timgoeller** [comment]
Unfortunetely not! We've decided to stick with webpack until this works.

**Comment by joshwooding** [comment]
@timgoeller I'm going to close this for now. Let us know if you're still encountering it.
