### ISSUE TITLE
Incompatible with vite-plugin-pages

### ISSUE THREAD

**Issue by viztor** [eirslett/storybook-builder-vite#64]
Without the plugin in main.js, vite will throw error can not import virtual:generated-pages, though when I do add the plugin, every request will be redirected to /virtual:xxx. which wouldn't work since it doesn't exist.

**Comment by micheartin** [comment]
I have a similar issue. My `package.json` contains:

```json
  "dependencies": {
    "vue": "^3.1.4",
    "vue-router": "^4.0.10"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^6.3.2",
    "@storybook/addon-essentials": "^6.3.2",
    "@storybook/addon-links": "^6.3.2",
    "@storybook/storybook-deployer": "^2.8.10",
    "@storybook/vue3": "^6.3.2",
    "@vitejs/plugin-vue": "^1.2.5",
    "@vue/compiler-sfc": "^3.1.4",
    "autoprefixer": "^10.3.1",
    "markdown-it-prism": "^2.1.8",
    "postcss": "^8.3.5",
    "sass": "^1.35.1",
    "storybook-builder-vite": "^0.0.12",
    "storybook-dark-mode": "^1.0.8",
    "tailwindcss": "^2.2.4",
    "typescript": "^4.3.5",
    "vite": "^2.4.2",
    "vite-plugin-md": "^0.6.7",
    "vite-plugin-pages": "^0.15.0"
  },
```

The plugin `vite-plugin-pages` [requires](https://github.com/hannoeru/vite-plugin-pages#overview) `import routes from "virtual:generated-pages"`.

But `yarn run start-storybook` has the following error:

```
yarn run v1.21.0
$ /home/a/j3/tealweb/node_modules/.bin/start-storybook
info @storybook/vue3 v6.3.4
info
info => Loading presets

info => Using cached manager
ERR! Error: The following dependencies are imported but could not be resolved:
ERR!
ERR!   virtual:generated-pages (imported by /home/a/j3/tealweb/src/router.ts)
ERR!
ERR! Are they installed?
ERR!     at optimizeDeps (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:73026:15)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!     at async runOptimize (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:73684:48)
ERR!     at async createServer (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:73713:9)
ERR!     at async Object.start (/home/a/j3/tealweb/node_modules/storybook-builder-vite/index.js:33:20)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/home/a/j3/tealweb/node_modules/@storybook/core-server/dist/cjs/dev-server.js:123:28)
ERR!     at async buildDevStandalone (/home/a/j3/tealweb/node_modules/@storybook/core-server/dist/cjs/build-dev.js:112:31)
ERR!     at async buildDev (/home/a/j3/tealweb/node_modules/@storybook/core-server/dist/cjs/build-dev.js:154:5)
ERR!  Error: The following dependencies are imported but could not be resolved:
ERR!
ERR!   virtual:generated-pages (imported by /home/a/j3/tealweb/src/router.ts)
ERR!
ERR! Are they installed?
ERR!     at optimizeDeps (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:73026:15)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!     at async runOptimize (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:73684:48)
ERR!     at async createServer (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:73713:9)
ERR!     at async Object.start (/home/a/j3/tealweb/node_modules/storybook-builder-vite/index.js:33:20)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/home/a/j3/tealweb/node_modules/@storybook/core-server/dist/cjs/dev-server.js:123:28)
ERR!     at async buildDevStandalone (/home/a/j3/tealweb/node_modules/@storybook/core-server/dist/cjs/build-dev.js:112:31)
ERR!     at async buildDev (/home/a/j3/tealweb/node_modules/@storybook/core-server/dist/cjs/build-dev.js:154:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: node /home/a/.yvm/versions/v1.22.10/bin/yarn.js run start-storybook
```

**Comment by viztor** [comment]
> I have a similar issue. My `package.json` contains:
> 
> ```json
>   "dependencies": {
>     "vue": "^3.1.4",
>     "vue-router": "^4.0.10"
>   },
>   "devDependencies": {
>     "@storybook/addon-actions": "^6.3.2",
>     "@storybook/addon-essentials": "^6.3.2",
>     "@storybook/addon-links": "^6.3.2",
>     "@storybook/storybook-deployer": "^2.8.10",
>     "@storybook/vue3": "^6.3.2",
>     "@vitejs/plugin-vue": "^1.2.5",
>     "@vue/compiler-sfc": "^3.1.4",
>     "autoprefixer": "^10.3.1",
>     "markdown-it-prism": "^2.1.8",
>     "postcss": "^8.3.5",
>     "sass": "^1.35.1",
>     "storybook-builder-vite": "^0.0.12",
>     "storybook-dark-mode": "^1.0.8",
>     "tailwindcss": "^2.2.4",
>     "typescript": "^4.3.5",
>     "vite": "^2.4.2",
>     "vite-plugin-md": "^0.6.7",
>     "vite-plugin-pages": "^0.15.0"
>   },
> ```
> 
> The plugin `vite-plugin-pages` [requires](https://github.com/hannoeru/vite-plugin-pages#overview) `import routes from "virtual:generated-pages"`.
> 
> But `yarn run start-storybook` has the following error:
> 
> ```
> yarn run v1.21.0
> $ /home/a/j3/tealweb/node_modules/.bin/start-storybook
> info @storybook/vue3 v6.3.4
> info
> info => Loading presets
> 
> info => Using cached manager
> ERR! Error: The following dependencies are imported but could not be resolved:
> ERR!
> ERR!   virtual:generated-pages (imported by /home/a/j3/tealweb/src/router.ts)
> ERR!
> ERR! Are they installed?
> ERR!     at optimizeDeps (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:73026:15)
> ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ERR!     at async runOptimize (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:73684:48)
> ERR!     at async createServer (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:73713:9)
> ERR!     at async Object.start (/home/a/j3/tealweb/node_modules/storybook-builder-vite/index.js:33:20)
> ERR!     at async Promise.all (index 0)
> ERR!     at async storybookDevServer (/home/a/j3/tealweb/node_modules/@storybook/core-server/dist/cjs/dev-server.js:123:28)
> ERR!     at async buildDevStandalone (/home/a/j3/tealweb/node_modules/@storybook/core-server/dist/cjs/build-dev.js:112:31)
> ERR!     at async buildDev (/home/a/j3/tealweb/node_modules/@storybook/core-server/dist/cjs/build-dev.js:154:5)
> ERR!  Error: The following dependencies are imported but could not be resolved:
> ERR!
> ERR!   virtual:generated-pages (imported by /home/a/j3/tealweb/src/router.ts)
> ERR!
> ERR! Are they installed?
> ERR!     at optimizeDeps (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:73026:15)
> ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ERR!     at async runOptimize (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:73684:48)
> ERR!     at async createServer (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:73713:9)
> ERR!     at async Object.start (/home/a/j3/tealweb/node_modules/storybook-builder-vite/index.js:33:20)
> ERR!     at async Promise.all (index 0)
> ERR!     at async storybookDevServer (/home/a/j3/tealweb/node_modules/@storybook/core-server/dist/cjs/dev-server.js:123:28)
> ERR!     at async buildDevStandalone (/home/a/j3/tealweb/node_modules/@storybook/core-server/dist/cjs/build-dev.js:112:31)
> ERR!     at async buildDev (/home/a/j3/tealweb/node_modules/@storybook/core-server/dist/cjs/build-dev.js:154:5)
> 
> WARN Broken build, fix the error above.
> WARN You may need to refresh the browser.
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> Command failed: node /home/a/.yvm/versions/v1.22.10/bin/yarn.js run start-storybook
> ```

Yeah, so the thing is storybook uses a dedicated vite config instead of your project vite config, so you might have to copy-paste relevant code.

**Comment by micheartin** [comment]
Thank you @viztor for your response.

I have carefully read the documentation https://storybook.js.org/docs/vue/configure
but my attempts have failed…

My file `.storybook/main.js`:

```js
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    'storybook-dark-mode'
  ],
  "core": {
    "builder": "storybook-builder-vite",
  },
  async viteFinal(config, { configType }) {
    config.resolve.alias = [
      { find: '@/', replacement: '/src/' },
      { find: 'vue', replacement: 'vue/dist/vue.esm-bundler.js' }
    ]
    return config;
  },
}
```
This previous `main.js` is fine for the command `yarn run build-storybook`.
But `yarn run start-storybook` fails.

When I add `const custom = require('../vite.config.js')` in the `.storybook/main.js`,
I got this error:

```
ERR! /home/a/j3/tealweb/vite.config.js:1
ERR! import path from "path"
ERR! ^^^^^^
ERR!
ERR! SyntaxError: Cannot use import statement outside a module
[...]
```

### Do you know how to copy the relevant part of my Vite config to the Storybook config ?

My `vite.config.js`:

```js
import path from "path"
import { defineConfig } from "vite"
import markdown from "vite-plugin-md"
import pages from "vite-plugin-pages"
import vue from "@vitejs/plugin-vue"
import prism from "markdown-it-prism"

export default defineConfig({
  plugins: [
    markdown({
      markdownItOptions: {
        html: true,
        linkify: true,
        typographer: true,
      },
      markdownItSetup(md) {
        md.use(prism)
      },
      wrapperClasses: "prose prose-sm m-auto text-left",
    }),
    pages({
      extensions: ["vue", "md"],
    }),
    vue({
      include: [/\.vue$/, /\.md$/],
    }),
  ],
  resolve: {
    alias: { "@/": `${path.resolve(__dirname, "src")}/` },
  },
})
```

**Comment by viztor** [comment]
@micheartin 
just do
```
config.plugins.push({
     ...your plugins (exclude the vue plugin since it's already included)
})
```

**Comment by micheartin** [comment]
Thank you @viztor 

Simplified version of my `.storybook/main.js`:

```js
const pagesPlugin = require("vite-plugin-pages")         // 🠜 add this

module.exports = {
  // typescript: ...
  // stories: ...
  // addons: ...
  // core: ...
  async viteFinal(config, { configType }) {
    config.resolve.alias = [
      { find: '@/', replacement: '/src/' },
      { find: 'vue', replacement: 'vue/dist/vue.esm-bundler.js' }
    ]
    config.plugins.push(                                 // 🠜
      pagesPlugin.default({ extensions: ["vue", "md"] }) // 🠜 add that
    )                                                    // 🠜
  },
}
```

But `yarn run start-storybook` produces the following Vite errors: 😕

```log
10:19:32 PM [vite] Internal server error: Cannot read property 'get' of undefined
  Plugin: vite:css-post
  File: /home/a/j3/tealweb/src/assets/index.css
      at TransformContext.transform (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:28172:56)
      at Object.transform (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:50885:53)
      at async transformRequest (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:66636:29)
      at async viteTransformMiddleware (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:66774:32)
10:19:35 PM [vite] Internal server error: Cannot read property 'get' of undefined
  Plugin: vite:css-post
  File: /home/a/j3/tealweb/src/App.vue?vue&type=style&index=0&lang.sass
      at TransformContext.transform (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:28172:56)
      at Object.transform (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:50885:53)
      at async transformRequest (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:66636:29)
      at async viteTransformMiddleware (/home/a/j3/tealweb/node_modules/vite/dist/node/chunks/dep-11db14da.js:66774:32)
```

My temporary workaround: remove `vite-plugin-pages` and set all routes by hand. 🤷‍♂️
I will try again in a couple of months… :wink:
