### ISSUE TITLE
Don't require MDX in order to work

### ISSUE THREAD

**Issue by gustavohenke** [eirslett/storybook-builder-vite#73]
Hey! 👋 

I've been converting an old project from poor slow Webpack to Vite lately, and I stumbled upon the [official blog post announcing your library](https://storybook.js.org/blog/storybook-for-vite/).
Thanks for it! My storybook changes will be so much faster! 🏎️ 

...however, this project only really uses `@storybook/react` itself + a couple of addons (e.g. viewport, controls and actions).
This means I'm not using the docs addon, despite it being among the [essential addons recommendation](https://storybook.js.org/docs/react/essentials/introduction).

And after installing this library, I noticed that I'm required to also install MDX stuff in order for it to work; e.g. this is the output:

```
info => Loading presets
ERR! Error: [vite-plugin-mdx] "@mdx-js/react" must be installed
ERR!     at resolveImport (<path>/node_modules/vite-plugin-mdx/dist/imports.js:29:23)
ERR!     at Object.assertImportExists (<path>/node_modules/vite-plugin-mdx/dist/imports.js:41:12)
ERR!     at <path>/node_modules/vite-plugin-mdx/dist/transform.js:18:19
ERR!     at Array.map (<anonymous>)
ERR!     at Object.createTransformer (<path>/node_modules/vite-plugin-mdx/dist/transform.js:17:50)
ERR!     at Object.configResolved (<path>/node_modules/vite-plugin-mdx/dist/index.js:38:43)
ERR!     at <path>/node_modules/vite/dist/node/chunks/dep-11db14da.js:75113:127
ERR!     at Array.map (<anonymous>)
ERR!     at resolveConfig (<path>/node_modules/vite/dist/node/chunks/dep-11db14da.js:75113:35)
ERR!     at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERR!     at async createServer (<path>/node_modules/vite/dist/node/chunks/dep-11db14da.js:73483:20)
ERR!     at async Object.start (<path>/node_modules/storybook-builder-vite/index.js:33:20)
```

Can I suggest that this library not be opinionated in this sense?

I'm not sure how storybook builders work yet, but it seems that omitting the following lines with some sort of configuration (e.g. does the consumer want documentation support) would be flexible enough.

https://github.com/eirslett/storybook-builder-vite/blob/3028e0fc2273544a1db36104e319bf3c5f35bf12/packages/storybook-builder-vite/vite-config.js#L14-L16

Thanks in advance!

**Comment by eirslett** [comment]
That's absolutely a potential improvement - I'm not quite sure how Storybook does this with Webpack and addons, I believe that each addon is responsible for injecting Webpack config into the build when the addon is registered. That only works with Webpack however, so we need to find some other solution for Vite.

There is also the problem with installing dependencies - if you want addon-docs in your Vite storybook, you also need the mdx dependencies for Vite, and it could be a less-than-ideal user experience for end users if they need to keep track of these manually. Maybe it could be solved by splitting storybook-builder-vite into multiple packages, like `@storybook-builder-vite/core`, `@storybook-builder-vite/addon-docs` (which would have the mdx stuff as a dependency), `@storybook-builder-vite/react` etc. etc. The builder is still in version 0.0.12, so it hasn't been prioritized yet.

For now, the builder is a "one size fits all", so you'll have to put up with the extra dead weight in node_modules. So it's a convenience/simplicity vs node_modules trade-off.

**Comment by gustavohenke** [comment]
I see, thanks!

If it's not a simple fix, I don't think you should be caring about splitting the package at such an early stage though!

**Comment by eirslett** [comment]
I'll close this for now, since it doesn't really have a simple solution.
