### ISSUE TITLE
addons is not defined when using "@storybook/addon-essentials"

### ISSUE THREAD

**Issue by mirabledictu** [eirslett/storybook-builder-vite#81]
https://github.com/storybookjs/storybook/issues/15706

It's a fresh Vite + Vue app and added storybook to it by running `npx sb@next init --builder storybook-builder-vite`. Then if you start with `yarn storybook`, you'll get this

![Screen Shot 2021-08-05 at 1 21 09 PM](https://user-images.githubusercontent.com/86201195/128297423-caa24ff4-4bbc-450d-ae28-4226e2d5d429.png)

**Comment by AddRaiser** [comment]
Fixed it by changing all @storybook/ stuff to 6.3.6 version

**Comment by heart-er** [comment]
@storybook @6.4.0-alpha.29 still has the same problem

**Comment by joshwooding** [comment]
@mirabledictu @heart-er I've tried this using a newer version of storybook-builder-vite and it's fixed for me. Here's the changes I made:

Bumped storybook libraries to 6.4.0-rc.6
Bumped storybook-builder-vite to 0.1.9
Added the framework field to main.js (https://github.com/storybookjs/storybook/issues/16296)

**Comment by joshwooding** [comment]
I'm going to close this for now. If you experience this again I'll re-open.
