### ISSUE TITLE
Stories not reloading

### ISSUE THREAD

**Issue by Kagigz** [eirslett/storybook-builder-vite#88]
Storybook version: 6.3.7

Hi, I set up storybook to use vite with my project's config.

The issue I have is that the stories are not reloaded at all, I have deleted the example files and created a new stories file, and updated my main.js file accordingly, but I still see the example stories (which don't exist anymore) and not my new story.

Here's my main.js:

```
const { loadConfigFromFile, mergeConfig } = require("vite")
const path = require("path");

module.exports = {

  "stories": [
    "../docs/*.stories.mdx",
    "../src/components/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "storybook-zeplin/register",
    "storybook-dark-mode",
    "@etchteam/storybook-addon-status"
  ],
  core: { builder: "storybook-builder-vite" },
  async viteFinal(config, { configType }) {
    const { config: userConfig } = await loadConfigFromFile(
      path.resolve(__dirname, "../vite.config.ts")
    );

    return mergeConfig(config, {
      ...userConfig
        })
  }
}
```

Do you have any idea how to fix this?
PS: I have tried deleting the .vite cache

Thanks

**Comment by IanVS** [comment]
This builder has its own vite config which you need to merge into yours, rather than only using your own config as you're doing.  Specifically, this is the part that is needed for story reloading: https://github.com/eirslett/storybook-builder-vite/blob/main/packages/storybook-builder-vite/vite-config.js#L64.

**Comment by Kagigz** [comment]
Thanks, I'll try fixing it. Does it work with Vue 3 as well?

**Comment by IanVS** [comment]
I believe so, although I don't use vue personally.  You should extend the existing config with yours, rather than replacing it wholesale, and I think you'll be good to go.
