### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by InsOpDe** [eirslett/storybook-builder-vite#89]
There is a problem when I try to install modules which rely on `global` or `process`:
```
util.js:109 Uncaught ReferenceError: process is not defined
    at node_modules/assert/node_modules/util/util.js (chunk-5RKL4QAC.js:652)
    at __require2 (chunk-IHTDASF6.js:17)
    at node_modules/assert/build/internal/assert/assertion_error.js (chunk-5RKL4QAC.js:1454)
    at __require2 (chunk-IHTDASF6.js:17)
    at node_modules/assert/build/assert.js (chunk-5RKL4QAC.js:2500)
    at __require2 (chunk-IHTDASF6.js:17)
    at chunk-5RKL4QAC.js:2985
    at node_modules/doctrine/lib/utility.js (chunk-5RKL4QAC.js:2986)
    at __require2 (chunk-IHTDASF6.js:17)
    at chunk-5RKL4QAC.js:2997
```

Like for example `next`

[I have created a repro](https://github.com/InsOpDe/storybook-vite-next-issue)
If you remove the next-dependency and reinstall, then everything works as expected.

Is there a way to polyfill `process` and/or `global`?
I have tried utilizing the rollup plugins but to no avail.

Approach was like this:
```
/* inside main.js */
async viteFinal(config) {
		config.build = {
			rollupOptions: {
				configDebug: true,
				plugins: [
					require('rollup-plugin-polyfill-node')()
				]
			}
		}
}
```

**Comment by IanVS** [comment]
There's no real way to polyfill `process` that I know of, since there is no `process` in the browser, and things like `cwd` have no meaning in the browser anyway.  You will likely need to either find dependencies which run natively in the browser, or submit PRs to those dependencies to enable them to do so.  Or, in my case, I knew that the only part of process that was needed was for a check on `NODE_ENV`, so I was able to do this in my tests:

```js
window.process = {
  env: {
    NODE_ENV: 'test',
  },
};
```

Depending on how it is being used, `global` can sometimes also be assigned from `window`.  

```js
window.global = window;
```

**Comment by eirslett** [comment]
The above answer is the easiest workaround. ^^
You can put it in preview-head.html.

**Comment by richardguerre** [comment]
@InsOpDe, the above workaround suggested by @IanVS didn't work for me, and I'm also using `next`. I went a little deeper and found that specifying `assert@1.5.0` and `util@0.11.1` worked.
I also found that going back to `next@11.1.0` works as those packages were not updated until `next@11.2.0`.

**Comment by MrJustice26** [comment]
I'm not sure if someone had the same issue in 2024, but here's a solution:
In my case adding those lines in return for `viteFinal` function inside `main.ts` storybook will fix the problem:
```js
define: {
   "process.env": process.env, // Polyfill for process.env
},
``` 

The whole `viteFinal` function:
```js
viteFinal: async (config) => {
    return {
      ...config,
      define: {
        "process.env": process.env,
      },
      resolve: {
        alias: [
          {
            find: "@",
            replacement: path.resolve(__dirname, ".."),
          },
        ],
      },
    };
  },
```

**Comment by IanVS** [comment]
@MrJustice26 keep in mind that if you do that, `process.env` will be stringified and string-replaced into any locations in your code using `process.env`, which might not be what you want.  Instead, it's normally recommended to add separate entries for each of the individual variables you need to access from within your code.
