### ISSUE TITLE
New dependencies found on each run even when dependencies are the same

### ISSUE THREAD

**Issue by ofirgeller** [eirslett/storybook-builder-vite#90]
When I startup the storybook in development mode the builder is logging many dependencies is new/changed and spends a lot of time "updating" them, this happens each time I start the storybook even if nothing changed anywhere in the codebase and no action that might effect packages was done  (like running 'yarn install').

it seems like the vite builder is creating files inside of the cache folder (default location) but that does not speed up the initial start at all.

Any ideas how to debug this or why it might be happening?

**Comment by eirslett** [comment]
We know about it, but nobody knows why it happens. You're free to investigate!

**Comment by jonrimmer** [comment]
I just noticed the same issue, overrode `config.server.force = false`, and it worked without breaking HMR. Maybe something else got fixed in the past few months?

**Comment by ofirgeller** [comment]
@jonrimmer or I might have miss tested. Will try to replicate soon.
