### ISSUE TITLE
stories not reloading with react

### ISSUE THREAD

**Issue by steveoh** [eirslett/storybook-builder-vite#94]
Storybook 6.4.0-alpha.34 for React started 

```js
// main.js
module.exports = {
  viteFinal(config) {
    config.plugins = [...config.plugins, require('vite-react-jsx').default()];

    return config;
  },
  stories: ['../src/**/**/*.stories.jsx'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
  core: {
    builder: 'storybook-builder-vite',
  },
};
```

Any time I update or change a file with a react component nothing happens. If I update a `blah.story.jsx` the page refreshes but the component is not updated. I do not see the changes until I kill the server and restart it. 

similar to #88

**Comment by IanVS** [comment]
Hmmm, that seems like hot module reloading for components is broken.  I wonder if it has anything to do with vite-react-jsx.  Is your project open source by any chance, or could you make a minimal reproduction?

**Comment by steveoh** [comment]
My project is open source yes, but I will try to make a minimal repro. Are the Get it now instructions on https://storybook.js.org/blog/storybook-for-vite/ a good place to start?

**Comment by steveoh** [comment]
So I am unsure what is up but I renamed the file, moved my components and stories over and those worked. I then deleted the original files and renamed the new files to match the ones I deleted and those continued to work. I have no idea what was going on but it sounds like some sort of caching issue?
