### ISSUE TITLE
addon/docs Cannot read property 'modernInlineRender' of undefined

### ISSUE THREAD

**Issue by KaiSpencer** [eirslett/storybook-builder-vite#95]
Unable to render Docs page.

Key Versions:
    "@storybook/addon-docs": "^6.4.0-alpha.35",
    "@storybook/addon-actions": "^6.4.0-alpha.35",
    "@storybook/addon-essentials": "^6.4.0-alpha.35",
    "@storybook/addon-links": "^6.4.0-alpha.35",
    "@storybook/react": "^6.4.0-alpha.35",
    "react": "^17.0.0",
    "vite": "^2.5.7",
    "storybook-builder-vite": "^0.0.12",

![Screenshot 2021-09-14 at 15 23 57](https://user-images.githubusercontent.com/51139521/133275887-f2263811-3839-410b-b288-284c7f265ec8.png)

**Comment by IanVS** [comment]
This seems to have been added in https://github.com/storybookjs/storybook/pull/15871.  We'll need to spend some time to figure out how to handle it, I guess.

**Comment by shilman** [comment]
Yowza. cc @tmeasday

**Comment by tmeasday** [comment]
@IanVS - https://github.com/storybookjs/storybook/pull/16044

Might be a good idea to always set `window.FEATURES`, but in the meantime we don't assume it in other places so I shouldn't assume it there.

**Comment by tmeasday** [comment]
Meanwhile we should absolutely discuss how to implement the equivalent of the new v7 store entry point in Vite: https://github.com/storybookjs/storybook/blob/next/lib/builder-webpack4/src/preview/virtualModuleModernEntry.js.handlebars

**Comment by IanVS** [comment]
@KaiSpencer could you please update storybook to `6.4.0-alpha.36` and try again?
