### ISSUE TITLE
iframe.html 404 files when hosted on GH Pages

### ISSUE THREAD

**Issue by jscastanos** [eirslett/storybook-builder-vite#96]
My current setup is to host the storybook in gh pages together with other documents. When I switch from using webpack to vite, I noticed that the build is not loading anymore. 

Then I notice this error on the console when loading the iframe.html.
![Screenshot from 2021-09-16 08-01-33](https://user-images.githubusercontent.com/37854603/133528538-1ec941a7-517b-4579-90d0-68406756ae3b.png)

When I inspect the network tab, it's requesting the file up one level

`https:/<org-name>/assets/vendor.81d71ea9.js`

when it should be

`https://<org-name>/<repo-name>/assets/vendor.81d71ea9.js`

So when I try to update the path from
```
<script type="module" crossorigin src="/assets/iframe.be2e2258.js"></script>
<link rel="modulepreload" href="/assets/vendor.a0fcc643.js">
<link rel="stylesheet" href="/assets/iframe.6e959737.css">
```

to

```
<script type="module" crossorigin src="./assets/iframe.be2e2258.js"></script>
<link rel="modulepreload" href="./assets/vendor.a0fcc643.js">
<link rel="stylesheet" href="./assets/iframe.6e959737.css">
```
adding `./` to all imports solved it. but I don't want to do it every deployment. 

How do I solve this one?

here's my current `./storybook/main.js`

```
const reactJsx = require("vite-react-jsx");
const path = require("path");

module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
  core: {
    builder: "storybook-builder-vite",
  },
  async viteFinal(config, { configType }) {
    // customize the Vite config here
    return {
      ...config,
      plugins: [...config.plugins, reactJsx.default()],
      entries: [
        `${path.relative(
          config.root,
          path.resolve(__dirname, "../stories")
        )}/**/*.stories.@(js|jsx|ts|tsx)`,
      ],
    };
  },
};

```

**Comment by jscastanos** [comment]
When the build is hosted in a local server, it's working fine. It only breaks on gh pages AFAIK

**Comment by imdongchen** [comment]
https://vitejs.dev/guide/build.html#public-base-path
Vote can configure the asset base path. Hope this helps!

**Comment by jscastanos** [comment]
@imdongchen Thank you. this one solved it 👍🏼 
So what I did is, I added `base: './'` to ./storybook/main.js

**Comment by openscript** [comment]
I would like to add a few lines here, so this can hopefully be found more easily by others. I ran into errors like...
```
Loading module from “https://openscript-ch.github.io/assets/iframe.e86ea686.js” was blocked because of a disallowed MIME type (“text/html”).
```

Inside the static files generated by `build-storybook` an absolute base path is used, which is wrong when storybook is hosted on a sub path like you need to do, when using Github Pages or similar.

As described here a possible minimal solution would be to change the vite configuration inside `.storybook/main.js` or whatever your main configuration of the storybook is called:

```
module.exports = {
  stories: [
    "../stories/Start.stories.mdx",
    "../stories/**/*.stories.mdx",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  addons: [
    {
      name: '@storybook/addon-docs',
      options: {
        configureJSX: true,
        transcludeMarkdown: true
      },
    },
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-storysource"
  ],
  core: {
    "builder": "storybook-builder-vite"
  },
  async viteFinal(config, { configType }) {
    if(configType === "PRODUCTION") {
      return {...config, base: './'};
    }
    return config;
  }
}
```
